
#ifndef STATE_ID_SCR_CREATE_SHARED_WALLET_H
#define STATE_ID_SCR_CREATE_SHARED_WALLET_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_CREATE_SHARED_WALLET_Entry(QVariant msg);
void SCR_CREATE_SHARED_WALLET_Exit(QVariant msg);
void EVT_CREATE_SHARED_WALLET_REQUEST_HANDLER(QVariant msg);
void EVT_CANCEL_SHARED_WALLET_REQUEST_HANDLER(QVariant msg);
void EVT_CREATE_SHARED_WALLET_BACK_HANDLER(QVariant msg);
void EVT_CREATE_SHARED_WALLET_REQUEST_CONFIGURATION_HANDLER(QVariant msg);
void EVT_RECOVER_SHARED_WALLET_REQUEST_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_CREATE_SHARED_WALLET_H
