
#ifndef STATE_ID_SCR_SOFTWARE_SIGNER_CONFIGURATION_H
#define STATE_ID_SCR_SOFTWARE_SIGNER_CONFIGURATION_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_SOFTWARE_SIGNER_CONFIGURATION_Entry(QVariant msg);
void SCR_SOFTWARE_SIGNER_CONFIGURATION_Exit(QVariant msg);
void EVT_SOFTWARE_SIGNER_REQUEST_CREATE_HANDLER(QVariant msg);
void EVT_ADD_SOFTWARE_SIGNER_RESULT_HANDLER(QVariant msg);
void EVT_SOFTWARE_SIGNER_CONFIGURATION_BACK_HANDLER(QVariant msg);
void EVT_SOFTWARE_SIGNER_CONFIGURATION_BACK_TO_WALLET_SIGNER_CONFIGURATION_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_SOFTWARE_SIGNER_CONFIGURATION_H
