
#ifndef STATE_ID_SCR_REMOTE_SIGNER_INFO_H
#define STATE_ID_SCR_REMOTE_SIGNER_INFO_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_REMOTE_SIGNER_INFO_Entry(QVariant msg);
void SCR_REMOTE_SIGNER_INFO_Exit(QVariant msg);
void EVT_REMOTE_SIGNER_INFO_HEALTH_CHECK_HANDLER(QVariant msg);
void EVT_REMOTE_SIGNER_INFO_EDIT_NAME_HANDLER(QVariant msg);
void EVT_REMOTE_SIGNER_INFO_IMPORT_SIGNATURE_HANDLER(QVariant msg);
void EVT_REMOTE_SIGNER_INFO_EXPORT_MESSAGE_HANDLER(QVariant msg);
void EVT_REMOTE_SIGNER_INFO_DELETE_REQUEST_HANDLER(QVariant msg);
void EVT_REMOTE_SIGNER_INFO_GET_XPUBS_HANDLER(QVariant msg);
void EVT_REMOTE_SIGNER_INFO_BACK_WALLET_INFO_HANDLER(QVariant msg);
void EVT_REMOTE_SIGNER_INFO_BACK_HOME_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_REMOTE_SIGNER_INFO_H
