
#ifndef STATE_ID_SCR_LOGIN_ONLINE_H
#define STATE_ID_SCR_LOGIN_ONLINE_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_LOGIN_ONLINE_Entry(QVariant msg);
void SCR_LOGIN_ONLINE_Exit(QVariant msg);
void EVT_LOGIN_ONLINE_CREATE_ACCOUNT_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_SIGN_IN_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_SWITCH_LOCAL_MODE_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_CHANGE_PASSWORD_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_FORGOT_PASSWORD_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_RECOVER_PASSWORD_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_STAY_SIGNED_IN_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_VERIFY_NEW_DEVICE_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_RESEND_CONFIRM_CODE_HANDLER(QVariant msg);
void EVT_LOGIN_ONLINE_LOGIN_SUCCEED_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_LOGIN_ONLINE_H
