
#ifndef STATE_ID_SCR_PRIMARY_KEY_ACCOUNT_H
#define STATE_ID_SCR_PRIMARY_KEY_ACCOUNT_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_PRIMARY_KEY_ACCOUNT_Entry(QVariant msg);
void SCR_PRIMARY_KEY_ACCOUNT_Exit(QVariant msg);
void EVT_SELECT_PRIMARY_KEY_ACCOUNT_REQUEST_HANDLER(QVariant msg);
void EVT_PRIMARY_KEY_BACK_TO_CREATE_ACCOUNT_HANDLER(QVariant msg);
void EVT_PRIMARY_KEY_ACCOUNT_BACK_HANDLER(QVariant msg);
void EVT_ADD_PRIMARY_KEY_REQUEST_HANDLER(QVariant msg);
void EVT_SHOW_SIGN_IN_BY_IMPORTING_THE_PRIMARY_KEY_REQUEST_HANDLER(QVariant msg);
void EVT_SCR_SIGN_IN_MANUALLY_REQUEST_HANDLER(QVariant msg);
void EVT_PRIMARY_KEY_BACK_TO_SIGN_IN_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_PRIMARY_KEY_ACCOUNT_H
