
#ifndef STATE_ID_SCR_BACKUP_SHARED_WALLET_H
#define STATE_ID_SCR_BACKUP_SHARED_WALLET_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_BACKUP_SHARED_WALLET_Entry(QVariant msg);
void SCR_BACKUP_SHARED_WALLET_Exit(QVariant msg);
void EVT_BACKUP_SHARED_WALLET_REQUEST_HANDLER(QVariant msg);
void EVT_BACKUP_SHARED_WALLET_SKIP_HANDLER(QVariant msg);
void EVT_BACKUP_SHARED_WALLET_EXPORT_BSMS_HANDLER(QVariant msg);
void EVT_BACKUP_SHARED_WALLET_BACK_HANDLER(QVariant msg);
void EVT_BACKUP_WALLET_DEVICE_REGISTRATION_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_BACKUP_SHARED_WALLET_H
