
#ifndef STATE_ID_SCR_ADD_HARDWARE_SIGNER_H
#define STATE_ID_SCR_ADD_HARDWARE_SIGNER_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_ADD_HARDWARE_SIGNER_Entry(QVariant msg);
void SCR_ADD_HARDWARE_SIGNER_Exit(QVariant msg);
void EVT_ADD_HARDWARE_SIGNER_ADD_MASTER_SIGNER_REQUEST_HANDLER(QVariant msg);
void EVT_ADD_HARDWARE_SIGNER_REFRESH_REQUEST_HANDLER(QVariant msg);
void EVT_ADD_HARDWARE_SIGNER_ADD_REMOTE_SIGNER_REQUEST_HANDLER(QVariant msg);
void EVT_ADD_HARDWARE_SIGNER_PROMT_PIN_REQUEST_HANDLER(QVariant msg);
void EVT_ADD_HARDWARE_SIGNER_SEND_PIN_REQUEST_HANDLER(QVariant msg);
void EVT_ADD_MASTER_SIGNER_RESULT_HANDLER(QVariant msg);
void EVT_ADD_REMOTE_SIGNER_RESULT_HANDLER(QVariant msg);
void EVT_ADD_HARDWARE_SIGNER_BACK_REQUEST_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_ADD_HARDWARE_SIGNER_H
