
#ifndef STATE_ID_SCR_MASTER_SIGNER_INFO_H
#define STATE_ID_SCR_MASTER_SIGNER_INFO_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_MASTER_SIGNER_INFO_Entry(QVariant msg);
void SCR_MASTER_SIGNER_INFO_Exit(QVariant msg);
void EVT_MASTER_SIGNER_INFO_EDIT_NAME_HANDLER(QVariant msg);
void EVT_MASTER_SIGNER_INFO_HEALTH_CHECK_HANDLER(QVariant msg);
void EVT_MASTER_SIGNER_INFO_REMOVE_REQUEST_HANDLER(QVariant msg);
void EVT_MASTER_SIGNER_INFO_PROMT_PIN_HANDLER(QVariant msg);
void EVT_MASTER_SIGNER_INFO_SEND_PIN_HANDLER(QVariant msg);
void EVT_MASTER_SIGNER_INFO_SEND_PASSPHRASE_HANDLER(QVariant msg);
void EVT_MASTER_SIGNER_INFO_BACK_REQUEST_HANDLER(QVariant msg);
void EVT_MASTER_SIGNER_INFO_BACK_WALLET_INFO_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_MASTER_SIGNER_INFO_H
