
#ifndef STATE_ID_SCR_SIGN_IN_BY_IMPORTING_THE_PRIMARY_KEY_H
#define STATE_ID_SCR_SIGN_IN_BY_IMPORTING_THE_PRIMARY_KEY_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_SIGN_IN_BY_IMPORTING_THE_PRIMARY_KEY_Entry(QVariant msg);
void SCR_SIGN_IN_BY_IMPORTING_THE_PRIMARY_KEY_Exit(QVariant msg);
void EVT_PRIMARY_KEY_ENTER_PASSPHRASE_REQUEST_HANDLER(QVariant msg);
void EVT_PRIMARY_KEY_ENTER_PASSPHRASE_SIGN_IN_REQUEST_HANDLER(QVariant msg);
void EVT_IMPORT_PRIMARY_KEY_WITH_SEED_REQUEST_HANDLER(QVariant msg);
void EVT_PRIMARY_KEY_ENTER_PASSPHRASE_SUCCEED_HANDLER(QVariant msg);
void EVT_SIGN_IN_BY_IMPORTING_THE_PRIMARY_KEY_BACK_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_SIGN_IN_BY_IMPORTING_THE_PRIMARY_KEY_H
