
#ifndef STATE_ID_SCR_WALLET_CHANGE_ADDRESSES_H
#define STATE_ID_SCR_WALLET_CHANGE_ADDRESSES_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_WALLET_CHANGE_ADDRESSES_Entry(QVariant msg);
void SCR_WALLET_CHANGE_ADDRESSES_Exit(QVariant msg);
void EVT_WALLET_CHANGE_ADDRESSES_GEN_NEW_ADDRESS_HANDLER(QVariant msg);
void EVT_WALLET_CHANGE_ADDRESSES_COPY_HANDLER(QVariant msg);
void EVT_WALLET_CHANGE_ADDRESS_BACK_REQUEST_HANDLER(QVariant msg);
void EVT_CHANGE_ADDRESS_BACK_SHARED_WALLET_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_WALLET_CHANGE_ADDRESSES_H
