
#ifndef STATE_ID_ROOT_H
#define STATE_ID_ROOT_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void ROOT_Entry(QVariant msg);
void ROOT_Exit(QVariant msg);
void EVT_STARTING_APPLICATION_LOCALMODE_HANDLER(QVariant msg);
void EVT_STARTING_APPLICATION_ONLINEMODE_HANDLER(QVariant msg);
void EVT_STARTING_APPLICATION_ONLINE_HWL_HANDLER(QVariant msg);
void EVT_SETTING_ACCOUNT_CHANGE_PASSWORD_HANDLER(QVariant msg);
void EVT_GOTO_HOME_WALLET_TAB_HANDLER(QVariant msg);
void EVT_ONS_CLOSE_REQUEST_HANDLER(QVariant msg);
void EVT_LOGIN_DB_REQUEST_HANDLER(QVariant msg);
void EVT_ROOT_PROMT_PIN_HANDLER(QVariant msg);
void EVT_ROOT_PROMT_PASSPHRASE_HANDLER(QVariant msg);
void EVT_LOGIN_MATRIX_REQUEST_HANDLER(QVariant msg);
void EVT_GOTO_HOME_CHAT_TAB_HANDLER(QVariant msg);
void EVT_ONLINE_ONS_CLOSE_REQUEST_HANDLER(QVariant msg);
void EVT_SHOW_TOAST_MESSAGE_HANDLER(QVariant msg);
void EVT_ROOT_UPDATE_PROFILE_HANDLER(QVariant msg);
void EVT_SHOW_CREATE_ACCOUNT_REQUEST_HANDLER(QVariant msg);
void EVT_SETTING_ONS_CLOSE_REQUEST_HANDLER(QVariant msg);
void EVT_GOTO_APP_SETTINGS_TAB_HANDLER(QVariant msg);

#endif // STATE_ID_ROOT_H
