
#ifndef STATE_ID_SCR_ADD_NEW_SOFTWARE_SIGNER_H
#define STATE_ID_SCR_ADD_NEW_SOFTWARE_SIGNER_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_ADD_NEW_SOFTWARE_SIGNER_Entry(QVariant msg);
void SCR_ADD_NEW_SOFTWARE_SIGNER_Exit(QVariant msg);
void EVT_ADD_NEW_SOFTWARE_SIGNER_BACK_HANDLER(QVariant msg);
void EVT_CREATE_NEW_SEED_HANDLER(QVariant msg);
void EVT_ADD_NEW_SOFTWARE_SIGNER_TO_WALLET_BACK_HANDLER(QVariant msg);
void EVT_NEW_SOFTWARE_SIGNER_BACK_TO_WALLET_SIGNER_CONFIGURATION_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_ADD_NEW_SOFTWARE_SIGNER_H
