
#ifndef STATE_ID_SCR_RECOVER_SOFTWARE_SIGNER_H
#define STATE_ID_SCR_RECOVER_SOFTWARE_SIGNER_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_RECOVER_SOFTWARE_SIGNER_Entry(QVariant msg);
void SCR_RECOVER_SOFTWARE_SIGNER_Exit(QVariant msg);
void EVT_RECOVER_SOFTWARE_SIGNER_REQUEST_HANDLER(QVariant msg);
void EVT_RECOVER_SOFTWARE_SIGNER_BACK_HANDLER(QVariant msg);
void EVT_RECOVER_SOFTWARE_SIGNER_SUCCEED_HANDLER(QVariant msg);
void EVT_RECOVER_SOFTWARE_SIGNER_TO_WALLET_BACK_HANDLER(QVariant msg);
void EVT_RECOVER_SOFTWARE_SIGNER_BACK_TO_WALLET_SIGNER_CONFIGURATION_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_RECOVER_SOFTWARE_SIGNER_H
