
#ifndef STATE_ID_SCR_TRANSACTION_INFO_H
#define STATE_ID_SCR_TRANSACTION_INFO_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_TRANSACTION_INFO_Entry(QVariant msg);
void SCR_TRANSACTION_INFO_Exit(QVariant msg);
void EVT_TRANSACTION_SIGN_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_EXPORT_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_EXPORT_QRCODE_HANDLER(QVariant msg);
void EVT_TRANSACTION_IMPORT_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_IMPORT_QRCODE_HANDLER(QVariant msg);
void EVT_TRANSACTION_BROADCAST_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_SET_MEMO_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_SCAN_DEVICE_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_REMOVE_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_SEND_PIN_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_PROMT_PIN_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_VERIFY_ADDRESS_HANDLER(QVariant msg);
void EVT_TRANSACTION_SEND_PASSPHRASE_HANDLER(QVariant msg);
void EVT_TRANSACTION_INFO_BACK_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_INFO_BACK_TO_CREATE_TRANSACTION_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_REPLACE_BY_FEE_REQUEST_HANDLER(QVariant msg);
void EVT_TRANSACTION_INFO_BACK_UTXO_INFO_HANDLE(QVariant msg);

#endif // STATE_ID_SCR_TRANSACTION_INFO_H
