
#ifndef STATE_ID_SCR_HOME_ONLINE_H
#define STATE_ID_SCR_HOME_ONLINE_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_HOME_ONLINE_Entry(QVariant msg);
void SCR_HOME_ONLINE_Exit(QVariant msg);
void EVT_HOME_ONLINE_ADD_SIGNER_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_CREATE_CHAT_ROOM_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_CREATE_DIRECT_CHAT_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_DELETE_DIRECT_ROOM_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_DELETE_ROOM_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_SEND_CHAT_CONTENT_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_CANCEL_SHARED_WL_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_CREATE_SHARED_WALLET_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_CANCEL_TRANSACTION_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_ADD_CONTACT_HANDLER(QVariant msg);
void EVT_HOME_SHOW_ALL_PENDING_CONTACT_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_SIGNER_AVAILABLE_FOR_SWL_HANDLER(QVariant msg);
void EVT_HOME_SHARED_WALLET_CONFIGURE_HANDLER(QVariant msg);
void EVT_HOME_BACKUP_SHARED_WALLET_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_SIGNER_UNAVAILABLE_FOR_SWL_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_APPSETTING_REQUEST_HANDLER(QVariant msg);
void EVT_HOME_SHARED_WL_SEND_REQUEST_HANDLER(QVariant msg);
void EVT_HOME_ONLINE_TRANSACTION_INFO_REQUEST_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_HOME_ONLINE_H
