
#ifndef STATE_ID_SCR_CREATE_TRANSACTION_H
#define STATE_ID_SCR_CREATE_TRANSACTION_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_CREATE_TRANSACTION_Entry(QVariant msg);
void SCR_CREATE_TRANSACTION_Exit(QVariant msg);
void EVT_CREATE_TRANSACTION_MAKE_DRAFT_TX_HANDLER(QVariant msg);
void EVT_CREATE_TRANSACTION_SAVE_REQUEST_HANDLER(QVariant msg);
void EVT_CREATE_TRANSACTION_UTXO_SORT_REQUEST_HANDLER(QVariant msg);
void EVT_CREATE_TRANSACTION_SIGN_REQUEST_HANDLER(QVariant msg);
void EVT_CREATE_TRANSACTION_BACK_REQUEST_HANDLER(QVariant msg);
void EVT_CREATE_TRANSACTION_SIGN_SUCCEED_HANDLER(QVariant msg);
void EVR_CREATE_TRANSACTION_BACK_UTXO_CONSILIDATE_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_CREATE_TRANSACTION_H
