
#ifndef STATE_ID_SCR_PRIMARY_KEY_CONFIGURATION_H
#define STATE_ID_SCR_PRIMARY_KEY_CONFIGURATION_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_PRIMARY_KEY_CONFIGURATION_Entry(QVariant msg);
void SCR_PRIMARY_KEY_CONFIGURATION_Exit(QVariant msg);
void EVT_PRIMARY_KEY_SIGN_IN_REQUEST_HANDLER(QVariant msg);
void EVT_PRIMARY_KEY_SIGN_IN_SUCCEED_HANDLER(QVariant msg);
void EVT_PRIMARY_KEY_CONFIGURATION_BACK_HANDLER(QVariant msg);
void EVT_PRIMARY_KEY_CONFIGURATION_FINISHED_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_PRIMARY_KEY_CONFIGURATION_H
