
#ifndef STATE_ID_SCR_SHARED_WL_DEVICE_REGISTRATION_H
#define STATE_ID_SCR_SHARED_WL_DEVICE_REGISTRATION_H

#include <QObject>
#include <QVariant>
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCR_SHARED_WL_DEVICE_REGISTRATION_Entry(QVariant msg);
void SCR_SHARED_WL_DEVICE_REGISTRATION_Exit(QVariant msg);
void EVT_SHARED_WALLET_EXPORT_COLDCARD_HANDLER(QVariant msg);
void EVT_SHARED_WALLET_EXPORT_QRCODE_HANDLER(QVariant msg);
void EVT_SHARED_WALLET_SKIP_REGISTRATION_HANDLER(QVariant msg);
void EVT_SHARED_WL_DEVICE_REGISTRAION_BACK_HANDLER(QVariant msg);

#endif // STATE_ID_SCR_SHARED_WL_DEVICE_REGISTRATION_H
