/**************************************************************************
 * This file is part of the Nunchuk software (https://nunchuk.io/)        *
 * Copyright (C) 2020-2022 Enigmo								          *
 * Copyright (C) 2022 Nunchuk								              *
 *                                                                        *
 * This program is free software; you can redistribute it and/or          *
 * modify it under the terms of the GNU General Public License            *
 * as published by the Free Software Foundation; either version 3         *
 * of the License, or (at your option) any later version.                 *
 *                                                                        *
 * This program is distributed in the hope that it will be useful,        *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 * GNU General Public License for more details.                           *
 *                                                                        *
 * You should have received a copy of the GNU General Public License      *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.  *
 *                                                                        *
 **************************************************************************/
.pragma library
// COMMON


// SCR_HOME.qml
var STR_QML_000 = qsTr("Wallets")
var STR_QML_001 = qsTr("Wallet details")
var STR_QML_002 = qsTr("Send")
var STR_QML_003 = qsTr("Receive")
var STR_QML_004 = qsTr("Quick receive")
var STR_QML_005  = qsTr("Copy")
var STR_QML_006 = qsTr("Verify on device")
var STR_QML_007 = qsTr("Check the correctness of this address on your device. Make sure your device is connected and unlocked.")
var STR_QML_008 = qsTr("Please check the address on your device")
var STR_QML_009 = qsTr("Member keys (%1 of %2)")
var STR_QML_010 = qsTr("Recent transactions")
var STR_QML_010_number = qsTr("(%1 total)")
var STR_QML_011 = qsTr("View all transactions")
var STR_QML_012 = qsTr("Mainnet")
var STR_QML_013 = qsTr("Testnet")
var STR_QML_014 = qsTr("Sample wallet")
var STR_QML_015 = qsTr("Keys")
var STR_QML_016 = qsTr("Sample key")
var STR_QML_017 = qsTr("Transaction fee")
var STR_QML_018 = qsTr("High priority")
var STR_QML_019 = qsTr("Medium priority")
var STR_QML_020 = qsTr("Low priority")

// SCR_ADD_WALLET.qml
var STR_QML_021 = qsTr("Add new wallet")
var STR_QML_022 = qsTr("Wallet configuration")
var STR_QML_023 = qsTr("Key configuration")
var STR_QML_024 = qsTr("Confirmation")
var STR_QML_025 = qsTr("Wallet name")
var STR_QML_026 = qsTr("Wallet description")
var STR_QML_027 = qsTr("Wallet type")
var STR_QML_028 = qsTr("Standard wallet")
var STR_QML_029 = qsTr("One-time Escrow Wallet")
var STR_QML_030 = qsTr("An Escrow Wallet is a special single-use wallet, designed to hold funds temporarily.")
var STR_QML_031 = qsTr("Advanced: Address Type (Default: Native Segwit)")
var STR_QML_032 = qsTr("Native Segwit (highest fee saving)")
var STR_QML_033 = qsTr("Nested Segwit (medium fee saving)")
var STR_QML_034 = qsTr("Legacy (no fee saving)")
var STR_QML_035 = qsTr("Cancel")
var STR_QML_036 = qsTr("Import Wallet")
var STR_QML_037 = qsTr("Recover via BSMS/descriptors/config file")
var STR_QML_038 = qsTr("Recover via QR code")
var STR_QML_039 = qsTr("Import QR Passport")
var STR_QML_040 = qsTr("Recover from COLDCARD")
var STR_QML_041 = qsTr("Import DB")
var STR_QML_042 = qsTr("NEXT: Key Setup")

//SCR_ADD_WALLET_SIGNER_CONFIGURATION.qml
var STR_QML_043 = qsTr("Choose from Existing Keys")
var STR_QML_044 = qsTr("Hardware")
var STR_QML_045 = qsTr("Air-gapped")
var STR_QML_046 = qsTr("Software")
var STR_QML_047 = qsTr("Foreign")
var STR_QML_048 = qsTr("Assign to wallet")
var STR_QML_049 = qsTr("Or Add a New Key")
var STR_QML_050 = qsTr("Add new key")
var STR_QML_051 = qsTr("Air-gapped keys supported")
var STR_QML_052 = qsTr("Key configuration")
var STR_QML_053 = qsTr("NUMBER OF KEYS:")
var STR_QML_054 = qsTr("(Maximum 15)")
var STR_QML_055 = qsTr("BIP32 Path: %1")
var STR_QML_056 = qsTr("Required signers:")
var STR_QML_057 = qsTr("of")
var STR_QML_058 = qsTr("Number of Signatures Required to Unlock Funds")
var STR_QML_059 = qsTr("Back to previous")
var STR_QML_060 = qsTr("Next: Review Wallet")

//SCR_ADD_WALLET_CONFIRMATION.qml
var STR_QML_061 = qsTr("Wallet & Key Configuration")
var STR_QML_062 = qsTr("Native Segwit")
var STR_QML_063 = qsTr("Nested Segwit")
var STR_QML_064 = qsTr("Legacy")
var STR_QML_065 = qsTr("Random")
var STR_QML_066 = qsTr("Address type")
var STR_QML_067 = qsTr("CREATED")
var STR_QML_068 = qsTr("Key configuration")
var STR_QML_069 = qsTr("Multisig")
var STR_QML_070 = qsTr("Single-sig")
var STR_QML_071 = qsTr("Get XPUBs")
var STR_QML_072 = qsTr("To create new wallets, additional XPUBs from the key are needed. Please plug in your key device, unlock, and press \"Get XPUBs\"")
var STR_QML_073 = qsTr("Create Wallet")
var STR_QML_074 = qsTr("Get XPUBs for key: ")
var STR_QML_075 = qsTr("Nunchuk is processing your key information")
var STR_QML_076 = qsTr("Creating new wallet")
var STR_QML_077 = qsTr("Please save the wallet configuration file (.bsms). You can use it to recover your wallet later using any BSMS-compatible software. BSMS is defined in BIP-0129: Bitcoin Secure Multisig Setup.")
var STR_QML_078 = qsTr("Save BSMS File")
var STR_QML_079 = qsTr("I'll do this later")
var STR_QML_080 = qsTr("*Note that this backup strictly contains information about the wallet. It does not include information on seeds or private keys.")
var STR_QML_081 = qsTr("Your wallet is almost ready")
var STR_QML_082 = qsTr("Wrapping up...")

//SCR_ADD_NEW_SIGNER.qml
var STR_QML_083 = qsTr("Add new key")
var STR_QML_084 = qsTr("Hardware key")
var STR_QML_085 = qsTr("Wired and air-gapped keys supported.")
var STR_QML_086 = qsTr("Add hardware key")
var STR_QML_087 = qsTr("Software key")
var STR_QML_088 = qsTr("The software key is managed by the app.")
var STR_QML_089 = qsTr("Add software key")
var STR_QML_090 = qsTr("Already added")
var STR_QML_091 = qsTr("Before you start")
var STR_QML_092 = qsTr("Please ensure to do the following before proceeding")
var STR_QML_093 = qsTr("Initialize the device key")
var STR_QML_094 = qsTr("Follow the vendor's instruction on how to set up your device with a seed phrase.")
var STR_QML_095 = qsTr("Unlock the device")
var STR_QML_096 = qsTr("To unlock the device, you might need to enter a <b>PIN</b> and/or a <b>PASSPHRASE</b> directly on the device screen.")
var STR_QML_097 = qsTr("Continue")
var STR_QML_098 = qsTr("The private key is stored and encrypted locally on this device. Please keep your device safe to prevent your key from being compromised.")
var STR_QML_099 = qsTr("Recover key with seed")
var STR_QML_100 = qsTr("Create new Key")

//SCR_ADD_HARDWARE_SIGNER.qml
var STR_QML_101 = qsTr("Add a hardware key")
var STR_QML_102 = qsTr("Key name")
var STR_QML_103 = qsTr("Add a wired key")
var STR_QML_104 = qsTr("Added")
var STR_QML_105 = qsTr("Refresh devices")
var STR_QML_106 = qsTr("Add key")
var STR_QML_107 = qsTr("Add an air-gapped key")
var STR_QML_108 = qsTr("Add air-gapped Key manually by entering your key spec.")
var STR_QML_109 = qsTr("XPUB")
var STR_QML_110 = qsTr("The data inputted is not valid")
var STR_QML_111 = qsTr("BIP32 Path")
var STR_QML_112 = qsTr("Master Key Fingerprint")
var STR_QML_113 = qsTr("Via QR Code")
var STR_QML_114 = qsTr("Export via QR")
var STR_QML_115 = qsTr("Export to Keystone/SeedSigner")
var STR_QML_116 = qsTr("Export to passport")
var STR_QML_117 = qsTr("Nunchuk is connecting to your device.")
var STR_QML_118 = qsTr("Key Health Check")
var STR_QML_119 = qsTr("Test signing message. Please wait and confirm the action on your key device.")
var STR_QML_120 = qsTr("Processing ...")
var STR_QML_121 = qsTr("Creating key: ")
var STR_QML_122 = qsTr("Please wait ...")
var STR_QML_123 = qsTr("XPUB or Public Key")
var STR_QML_124 = qsTr("You can also enter the Public Key if used for Escrow Wallets")
var STR_QML_125 = qsTr("OR")

//SCR_ADD_MASTER_SIGNER_RESULT.qml
var STR_QML_126 = qsTr("Key info")
var STR_QML_127 = qsTr("Key spec")
var STR_QML_128 = qsTr("Used in wallets")
var STR_QML_129 = qsTr("Health check")
var STR_QML_130 = qsTr("Custom test message")
var STR_QML_131 = qsTr("Message to sign")
var STR_QML_132 = qsTr("Signature")
var STR_QML_133 = qsTr("Health Check Result Details...")
var STR_QML_134 = qsTr("Your key is healthy.")
var STR_QML_135 = qsTr("No signature generated. Please check your connection and make sure you have unlocked the device.")
var STR_QML_136 = qsTr("Plug in your key to perform a health check.")
var STR_QML_137 = qsTr("Run health check")
var STR_QML_138 = qsTr("Confirm & Close")
var STR_QML_139 = qsTr("Close")
var STR_QML_140 = qsTr("Health check key: ")
var STR_QML_141 = qsTr("Please Confirm on the Key Device")

//SCR_ADD_NEW_SOFTWARE_SIGNER.qml
var STR_QML_142 = qsTr("New seed")
var STR_QML_143 = qsTr("Please take a moment to write down this seed phrase. <b>It is the backup for your key.</b>")
var STR_QML_144 = qsTr("Never share the seed phrase with anyone. Avoid having a digital copy.")

//SCR_ADD_REMOTE_SIGNER_RESULT.qml
var STR_QML_145 = qsTr("Key Info (Air-Gapped)")
var STR_QML_146 = qsTr("The Key has been added successfully!")
var STR_QML_147 = qsTr("Air-gapped key spec")
var STR_QML_148 = qsTr("Public Key:")
var STR_QML_149 = qsTr("XPUB:")
var STR_QML_150 = qsTr("BIP32 Path:")
var STR_QML_151 = qsTr("Master Key Fingerprint:")
var STR_QML_152 = qsTr("EXPORT MESSAGE")
var STR_QML_153 = qsTr("IMPORT MESSAGE")
var STR_QML_154 = qsTr("Health Check Result")
var STR_QML_155 = qsTr("Your key is healthy.")
var STR_QML_156 = qsTr("That doesn't seem right. Please double check the signature.")

//SCR_APP_SETTINGS.qml
var STR_QML_157 = qsTr("Settings")
var STR_QML_158 = qsTr("Display unit")
var STR_QML_159 = qsTr("Show fixed precision")
var STR_QML_160 = qsTr("satoshi (1 BTC = 100,000,000 sat)")
var STR_QML_161 = qsTr("Database encryption")
var STR_QML_162 = qsTr("Enter passphrase")
var STR_QML_163 = qsTr("Passphrase must have at least 8 characters.")
var STR_QML_164 = qsTr("Passphrase changed successfully.")
var STR_QML_165 = qsTr("Could not change your passphrase")
var STR_QML_166 = qsTr("Re-enter to confirm passphrase")
var STR_QML_167 = qsTr("Change passphrase")
var STR_QML_168 = qsTr("Custom HWI Driver")
var STR_QML_169 = qsTr("Enter Path to Your HWI Executable")
var STR_QML_170 = qsTr("Network settings")
var STR_QML_171 = qsTr("Connect to Electrum server")
var STR_QML_172 = qsTr("Connect to Core node")
var STR_QML_173 = qsTr("Mainnet Server")
var STR_QML_174 = qsTr("Testnet Server")
var STR_QML_175 = qsTr("Set SSL certificate")
var STR_QML_176 = qsTr("Enter Path to Your SSL Certificate")
var STR_QML_177 = qsTr("Enable TOR proxy")
var STR_QML_178 = qsTr("Proxy address")
var STR_QML_179 = qsTr("Port")
var STR_QML_180 = qsTr("Proxy name")
var STR_QML_181 = qsTr("Proxy password")
var STR_QML_182 = qsTr("If you switch to Core for the first time and your wallet has a history, a blockchain rescan would be needed to reconstruct the wallet. This process might take some time.")
var STR_QML_183 = qsTr("RPC host")
var STR_QML_184 = qsTr("RPC Port")
var STR_QML_185 = qsTr("RPC username")
var STR_QML_186 = qsTr("RPC password")
var STR_QML_187 = qsTr("Manual rescan")
var STR_QML_188 = qsTr("Block height")
var STR_QML_189 = qsTr("Rescan")
var STR_QML_190 = qsTr("Please wait, processing ...")
var STR_QML_191 = qsTr("Apply changes?")
var STR_QML_192 = qsTr("Please note that some changes require an app reboot.")
var STR_QML_193 = qsTr("Discard changes")
var STR_QML_194 = qsTr("Apply")
var STR_QML_195 = qsTr("Restart application")
var STR_QML_196 = qsTr("Please restart the application to apply the new settings.")
var STR_QML_197 = qsTr("Restart")

//SCR_CHANGE_ADDRESS.qml
var STR_QML_198 = qsTr("Change addresses")
var STR_QML_199 = qsTr("Unused address (%1)")
var STR_QML_200 = qsTr("Used address (%1)")
var STR_QML_201 = qsTr("An address is marked as used as soon as money is deposited into it. For better privacy, reusing addresses is not recommended.")
var STR_QML_202 = qsTr("Generate new address")
var STR_QML_203 = qsTr("UNUSED")
var STR_QML_204 = qsTr("USED")
var STR_QML_205 = qsTr("Copy address")

//SCR_CREATE_NEW_SEED.qml
var STR_QML_206 = qsTr("Confirm seed")
var STR_QML_207 = qsTr("Please confirm the following words.")
var STR_QML_208 = qsTr("Confirm seed fail")

//SCR_CREATE_TRANSACTION.qml
var STR_QML_209 = qsTr("Replace-by-Fee")
var STR_QML_210 = qsTr("Consolidate outputs")
var STR_QML_211 = qsTr("Confirm transaction")
var STR_QML_212 = qsTr("Escrow")
var STR_QML_213 = qsTr("Send to address")
var STR_QML_214 = qsTr("Amount")
var STR_QML_215 = qsTr("Estimated fee")
var STR_QML_216 = qsTr("Total amount")
var STR_QML_217 = qsTr("Change address")
var STR_QML_218 = qsTr("Private note")
var STR_QML_219 = qsTr("Signatures")
var STR_QML_220 = qsTr("Pending %1 signatures")
var STR_QML_221 = qsTr("Manual coin selection")
var STR_QML_222 = qsTr("Output address")
var STR_QML_223 = qsTr("CONF.")
var STR_QML_224 = qsTr("AMT")
var STR_QML_225 = qsTr("Customize fee setting")
var STR_QML_226 = qsTr("Subtract fee from send amount")
var STR_QML_227 = qsTr("The fee will be deducted from the amount being sent. The recipient will receive less bitcoins than you enter in the amount field.")
var STR_QML_228 = qsTr("Manual fee rate")
var STR_QML_229 = qsTr("You may bump the fee rate later using Replace By Fee.")
var STR_QML_230 = qsTr("The new fee rate needs to be higher than %1.")
var STR_QML_231 = qsTr("the original fee (%1)")
var STR_QML_232 = qsTr("Priority rate:")
var STR_QML_233 = qsTr("Standard rate:")
var STR_QML_234 = qsTr("Economical rate:")
var STR_QML_235 = qsTr("Confirm and create transaction")
var STR_QML_236 = qsTr("Creating transaction")

//SCR_LOGIN_ONLINE.qml
var STR_QML_237 = qsTr("Please enter your passphrase")
var STR_QML_238 = qsTr("The passphrase you entered is incorrect.")
var STR_QML_239 = qsTr("Enter The Dragon")

//SCR_MASTER_SIGNER_INFO.qml
var STR_QML_240 = qsTr("Key info")
var STR_QML_241 = qsTr("Remove key")
var STR_QML_242 = qsTr("Confirmation")
var STR_QML_243 = qsTr("Are you sure you want to remove this key?")
var STR_QML_244 = qsTr("Type \"DELETE\" to confirm deletion.")
var STR_QML_245 = qsTr("Cancel")
var STR_QML_246 = qsTr("Delete")

//SCR_RECEIVE.qml
var STR_QML_247 = qsTr("Receive funds")
var STR_QML_248 = qsTr("Save as quick receive")
var STR_QML_249 = qsTr("Address balance:")

//SCR_RECOVER_SOFTWARE_SIGNER.qml
var STR_QML_250 = qsTr("Recover an existing seed")
var STR_QML_251 = qsTr("Please enter the seed.")
var STR_QML_252 = qsTr("Import signature")
var STR_QML_253 = qsTr("That doesn't seem right. Please double check your signature.")
var STR_QML_254 = qsTr("Make sure this key is no longer used in your wallets")
var STR_QML_255 = qsTr("Deleting this key can affect the wallets that are using it")

//SCR_REMOTE_SIGNER_INFO.qml
var STR_QML_256 = qsTr("Send funds")
var STR_QML_257 = qsTr("Create transaction")
var STR_QML_258 = qsTr("Batched transaction (advanced)")
var STR_QML_259 = qsTr("Wallet balance:")
var STR_QML_260 = qsTr("To address")
var STR_QML_261 = qsTr("Amount")
var STR_QML_262 = qsTr("Send all")
var STR_QML_263 = qsTr("Add recipient")
var STR_QML_264 = qsTr("Private note")
var STR_QML_265 = qsTr("Continue")

//SCR_SOFTWARE_SIGNER_CONFIGURATION.qml
var STR_QML_266 = qsTr("Give your key a name")
var STR_QML_267 = qsTr("Key name")
var STR_QML_268 = qsTr("Set a passphrase (optional)")
var STR_QML_268_PKEY = qsTr("Set a passphrase")
var STR_QML_269 = qsTr("Passphrase adds another layer of security to your key. You will need to enter the passphrase every time you sign using this key. You can think of it as the 25th word of your seed phrase. Passphrase is optional.")
var STR_QML_270 = qsTr("<b>Passphrase</b>")
var STR_QML_271 = qsTr("Confirm passphrase")
var STR_QML_272 = qsTr("Please back up your passphrase along with the seed. You will need both to recover your key.")
var STR_QML_273 = qsTr("Set passphrase")
var STR_QML_274 = qsTr("The confirm passphrase doesn't match")
var STR_QML_275 = qsTr("I don't need a passphrase")
var STR_QML_276 = qsTr("Processing...")
var STR_QML_277 = qsTr("The key is being added. Once complete, you can assign this key to new wallets.")

//SCR_TRANSACTION_HISTORY.qml
var STR_QML_278 = qsTr("Wallet info")
var STR_QML_279 = qsTr("Status")
var STR_QML_280 = qsTr("Transaction memo")
var STR_QML_281 = qsTr("Transaction data")

//SCR_TRANSACTION_INFO.qml
var STR_QML_282 = qsTr("Transaction info")
var STR_QML_283 = qsTr("Pending signatures")
var STR_QML_284 = qsTr("Ready to broadcast")
var STR_QML_285 = qsTr("Network rejected")
var STR_QML_286 = qsTr("Pending confirmations")
var STR_QML_287 = qsTr("Confirmations")
var STR_QML_288 = qsTr("Replaced by Fee")
var STR_QML_289 = qsTr("Member keys")
var STR_QML_290 = qsTr("Receive address")
var STR_QML_291 = qsTr("View on Blockstream Explorer")
var STR_QML_292 = qsTr("Remove transaction")
var STR_QML_293 = qsTr("Replace-by-Fee")
var STR_QML_294 = qsTr("Export transaction")
var STR_QML_295 = qsTr("Start broadcasting")
var STR_QML_296 = qsTr("Cancel transaction")
var STR_QML_297 = qsTr("Signing transaction")
var STR_QML_298 = qsTr("Please confirm to sign on the key device")
var STR_QML_299 = qsTr("Export/Import transaction")
var STR_QML_300 = qsTr("Export PSBT")
var STR_QML_301 = qsTr("Import PSBT")
var STR_QML_302 = qsTr("Import from Keystone/SeedSigner")
var STR_QML_303 = qsTr("Import from Passport/SeedSigner")

//SCR_UTXO_CONSOLIDATE.qml
var STR_QML_304 = qsTr("Consolidate outputs")
var STR_QML_305 = qsTr("Selected total:")

//SCR_UTXO_INFO.qml
var STR_QML_306 = qsTr("Unspent Output Info")
var STR_QML_307 = qsTr("VOUT")
var STR_QML_308 = qsTr("TRANSACTION ID")
var STR_QML_309 = qsTr("ADDRESS")
var STR_QML_310 = qsTr("SCRIPTPUBKEY")
var STR_QML_311 = qsTr("RELATED TRANSACTION")

//SCR_UTXOS.qml
var STR_QML_312 = qsTr("Unspent Outputs")
var STR_QML_313 = qsTr("UNSPENT OUTPUT")
var STR_QML_314 = qsTr("CONFIRMATIONS")
var STR_QML_315 = qsTr("UTXO Data")

//SCR_WALLET_INFO.qml
var STR_QML_316 = qsTr("Coldcard requires a multisig configuration file before it can sign transactions. Please choose \"Export\" > \"Export To Coldcard\", then copy the resulting file over to Coldcard.")
var STR_QML_317 = qsTr("Wallet name")
var STR_QML_318 = qsTr("Wallet description")
var STR_QML_319 = qsTr("Wallet type")
var STR_QML_320 = qsTr("Keys:")
var STR_QML_321 = qsTr("XFP:")
var STR_QML_322 = qsTr("Last heath check:")
var STR_QML_323 = qsTr("Export")
var STR_QML_324 = qsTr("Export Wallet BSMS File")
var STR_QML_325 = qsTr("Export Wallet Database")
var STR_QML_326 = qsTr("Export Transaction History (CSV)")
var STR_QML_327 = qsTr("Export UTXOs (CSV)")
var STR_QML_328 = qsTr("Export wallet to Coldcard")
var STR_QML_329 = qsTr("Export to Keystone/SeedSigner as QR code")
var STR_QML_330 = qsTr("Export to Passport/SeedSigner as QR code")
var STR_QML_331 = qsTr("More options")
var STR_QML_332 = qsTr("Delete wallet")
var STR_QML_333 = qsTr("*Export data do not include seeds or private keys.")
var STR_QML_334 = qsTr("Confirmation")
var STR_QML_335 = qsTr("Once you delete the wallet, all your data (and metadata such as transaction private notes) will be gone. We recommend backing up the wallet descriptors or database, if you want to recover the wallet later.")

//SCR_ASSIGN_SIGNER_TO_SHARED_WALLET.qml
var STR_QML_336 = qsTr("Assign key")
var STR_QML_337 = qsTr("Assign at least 1 key to the wallet")
var STR_QML_338 = qsTr(" slot left in the wallet")
var STR_QML_339 = qsTr("Info")
var STR_QML_340 = qsTr("You have exceeded your signer limit for this wallet. All members in the group must participate in the wallet.")
var STR_QML_341 = qsTr("Got it")

//SCR_BACKUP_SHARED_WALLET.qml
var STR_QML_342 = qsTr("Backup")
var STR_QML_343 = qsTr("Please save your wallet configuration")
var STR_QML_344 = qsTr("Losing the wallet configuration file alone does not compromise your funds, but you should still keep it safe to protect your privacy, as whoever has the configuration can monitor transactions in the wallet.")
var STR_QML_345 = qsTr("Tip: you need both the keys and the configuration to perform a wallet recovery.")
var STR_QML_346 = qsTr("I'll do this later")
var STR_QML_347 = qsTr("Export wallet configuration")

//SCR_CONFIGURE_SHARED_WALLET.qml
var STR_QML_348 = qsTr("Configure collaborative wallet")
var STR_QML_349 = qsTr("Total number of signers")
var STR_QML_350 = qsTr("Total number of signers in the wallet")
var STR_QML_351 = qsTr("Required signers")
var STR_QML_352 = qsTr("Number of signatures required to unlock funds")
var STR_QML_353 = qsTr("Current wallet config")

//SCR_CONTACT_PENDING_REQUEST.qml
var STR_QML_354 = qsTr("Pending requests")
var STR_QML_355 = qsTr("Received")
var STR_QML_356 = qsTr("Sent")

//SCR_CREATE_SHARED_WALLET.qml
var STR_QML_357 = qsTr("Create collaborative wallet")
var STR_QML_358 = qsTr("Customize wallet type")
var STR_QML_359 = qsTr("Defaut: Native Segwit")
var STR_QML_360 = qsTr("Highest fee saving")
var STR_QML_361 = qsTr("Medium fee saving")
var STR_QML_362 = qsTr("No fee saving")
var STR_QML_363 = qsTr("Customize address type")
var STR_QML_364 = qsTr("Defaut: Standard wallet")
var STR_QML_365 = qsTr("A special single-use wallet, designed to hold funds temporarily.")

//SCR_HOME_ONLINE.qml
var STR_QML_366 = qsTr("Messages")
var STR_QML_367 = qsTr("Direct messages")
var STR_QML_368 = qsTr("To create a collaborative wallet, please add your contacts then start a conversation.")
var STR_QML_369 = qsTr("Add Contact")
var STR_QML_370 = qsTr("Contacts")
var STR_QML_371 = qsTr("Pending requests")
var STR_QML_372 = qsTr("See all")
var STR_QML_373 = qsTr("Contact list")
var STR_QML_374 = qsTr("Delete contact")
var STR_QML_375 = qsTr("You have no contacts yet.")
var STR_QML_376 = qsTr("Completed")
var STR_QML_377 = qsTr("Pending finalization")
var STR_QML_378 = qsTr("Pending keys")
var STR_QML_379 = qsTr("Welcome to messages")
var STR_QML_380 = qsTr("Let’s begin by getting you some friends")
var STR_QML_381 = qsTr("Edit group name")
var STR_QML_382 = qsTr("Group name")
var STR_QML_383 = qsTr("Save group name")
var STR_QML_384 = qsTr("Add people")
var STR_QML_385 = qsTr("Enter a name or email")
var STR_QML_386 = qsTr("Add member")
var STR_QML_387 = qsTr("Please wait while the app is syncing ...")
var STR_QML_388 = qsTr("Data merge in progress ...")
var STR_QML_389 = qsTr("Please allow a moment for data to complete merging.")

//SCR_LOGIN_ONLINE.qml
var STR_QML_390 = qsTr("Welcome to Nunchuk")
var STR_QML_391 = qsTr("The gold standard of Bitcoin custody.")
var STR_QML_392 = qsTr("Create a new account")
var STR_QML_393 = qsTr("Your name")
var STR_QML_394 = qsTr("Email address")
var STR_QML_395 = qsTr("Create an account")
var STR_QML_396 = qsTr("This field is required")
var STR_QML_397 = qsTr("Back to previous")
var STR_QML_398 = qsTr("By creating an account, you agree to our <a href='%1'>Terms and Conditions</a> and <a href='%2'>Privacy Policy</a>")
var STR_QML_399 = qsTr("Can't create account")
var STR_QML_400 = qsTr("We’ve sent a temporary password to %1. Please change your password.")
var STR_QML_401 = qsTr("Temporary password")
var STR_QML_402 = qsTr("New password")
var STR_QML_403 = qsTr("Confirm new password")
var STR_QML_404 = qsTr("The password confirmation does not match.")
var STR_QML_405 = qsTr("Change password")
var STR_QML_406 = qsTr("New password must be different from the old password")
var STR_QML_407 = qsTr("Can't change password")
var STR_QML_408 = qsTr("Reset password")
var STR_QML_409 = qsTr("Enter the email address you used to register with Nunchuk and we'll send you a temporary password for you to sign in.")
var STR_QML_410 = qsTr("Send a new temporary password")
var STR_QML_411 = qsTr("Can't send request")
var STR_QML_412 = qsTr("We’ve sent a temporary password to %1. Please use it to change your password.")
var STR_QML_413 = qsTr("Temporary password")
var STR_QML_414 = qsTr("Can't reset password")
var STR_QML_415 = qsTr("Sign in to continue")
var STR_QML_416 = qsTr("Password")
var STR_QML_417 = qsTr("Stay signed in")
var STR_QML_418 = qsTr("Forgot password?")
var STR_QML_419 = qsTr("Sign in")
var STR_QML_420 = qsTr("Continue as guest")
var STR_QML_421 = qsTr("By creating an account or continuing as guest, you agree to our <a href='%1'>Terms and Conditions</a> and <a href='%2'>Privacy Policy</a>")
var STR_QML_422 = qsTr("We use email as the user ID for collaborative wallet and interpersonal messaging features. For stand-alone wallet that doesn’t require email sign up, please use guest mode.")
var STR_QML_423 = qsTr("Account does not exist")
var STR_QML_424 = qsTr("Enter confirmation code")
var STR_QML_425 = qsTr("Enter the confirmation code we sent to your email. <a href='dummycode.tbd'>Resend code</a>")
var STR_QML_426 = qsTr("Confirmation code")
var STR_QML_427 = qsTr("Confirm")

//SCR_ONLINE_ADD_CONTACTS.qml
var STR_QML_428 = qsTr("Add contacts")
var STR_QML_429 = qsTr("Enter emails or usernames, separated by spaces")
var STR_QML_430 = qsTr("Send invitation")
var STR_QML_431 = qsTr("These contacts are not on Nunchuk. Would you like to send an invite?")
var STR_QML_432 = qsTr("No")
var STR_QML_433 = qsTr("Yes")

//SCR_REVIEW_SHARED_WALLET.qml
var STR_QML_434 = qsTr("Review collaborative wallet")
var STR_QML_435 = qsTr("Wallet configuration")
var STR_QML_436 = qsTr("Address type")

//SCR_SHARED_WALLET_CONFIGURE.qml
var STR_QML_437 = qsTr("Wallet config")
var STR_QML_438 = qsTr("Collab")
var STR_QML_439 = qsTr("All keys have been assigned")
var STR_QML_440 = qsTr("Pending %1 keys to be assigned")
var STR_QML_440_ = qsTr("Pending 1 key to be assigned")
var STR_QML_441 = qsTr("Cancel wallet")
var STR_QML_442 = qsTr("Finalize wallet")
var STR_QML_443 = qsTr("Continue to assign signers")
var STR_QML_444 = qsTr("More options")
var STR_QML_445 = qsTr("Export wallet to Coldcard")
var STR_QML_446 = qsTr("Show as QR code")

//SCR_STARTING_CREATE_SIGNER.qml
var STR_QML_447 = qsTr("You don’t have any key yet.")
var STR_QML_448 = qsTr("Please add a key before assigning it to the collaborative wallet")
var STR_QML_449 = qsTr("Take me to add a key")

//SCR_UPDATE_PROFILE.qml
var STR_QML_450 = qsTr("Update profile")
var STR_QML_451 = qsTr("Name")
var STR_QML_452 = qsTr("Upload photo")
var STR_QML_453 = qsTr("Remove photo")
var STR_QML_454 = qsTr("Save changes")

//Component *.qml
var STR_QML_455 = qsTr("Health check")
var STR_QML_456 = qsTr("Replaced")
var STR_QML_457 = qsTr("Enter your passphrase")
var STR_QML_458 = qsTr("Your PIN Number")
var STR_QML_459 = qsTr("Send PIN")
var STR_QML_460 = qsTr("Update profile")
var STR_QML_461 = qsTr("Settings")
var STR_QML_462 = qsTr("Sign out")
var STR_QML_463 = qsTr("Welcome to Wallet Manager")
var STR_QML_464 = qsTr("Congrats on your first key! Now you can create a new wallet using the key you have added.")
var STR_QML_465 = qsTr("Start managing your Bitcoin wallets all in one place by adding a new key.")
var STR_QML_466 = qsTr("Are you sure you want to cancel this wallet?")
var STR_QML_467 = qsTr("Ignore")
var STR_QML_468 = qsTr("Accept")
var STR_QML_469 = qsTr("Pending")
var STR_QML_470 = qsTr("Withdraw request")
var STR_QML_471 = qsTr("No name")
var STR_QML_472 = qsTr("Members")
var STR_QML_473 = qsTr("Would you like to create a collaborative wallet?")
var STR_QML_474 = qsTr("A collaborative wallet is one of the safest ways to store your bitcoin because it eliminates single points of failure. Want to learn more about collaborative wallets? <a href='%1'>Read our guide.</a>")
var STR_QML_475 = qsTr("No, thanks")
var STR_QML_476 = qsTr("Create a collaborative wallet")
var STR_QML_477 = qsTr("Delivered")
var STR_QML_478 = qsTr("Sending")
var STR_QML_479 = qsTr("Unknown")
var STR_QML_480 = qsTr("Creating a %1/%2 %3 wallets")
var STR_QML_481 = qsTr("escrow")
var STR_QML_482 = qsTr("standard")
var STR_QML_483 = qsTr("Canceled")
var STR_QML_484 = qsTr("View config")
var STR_QML_485 = qsTr("Creating a <b>%1 %2</b>")
var STR_QML_486 = qsTr("Pending %1 keys")
var STR_QML_487 = qsTr("Deny wallet")
var STR_QML_488 = qsTr("View details")
var STR_QML_489 = qsTr("Do it now")
var STR_QML_490 = qsTr("N/A")
var STR_QML_491 = qsTr("Sending to ")
var STR_QML_492 = qsTr("Confirmed")
var STR_QML_493 = qsTr("Enough signatures collected")
var STR_QML_494 = qsTr("signatures")
var STR_QML_495 = qsTr("signature")
var STR_QML_496 = qsTr("Sign transaction")
var STR_QML_497 = qsTr("Broadcast transaction")
var STR_QML_498 = qsTr("The transaction to <b>%1...%2</b> has been confirmed")
var STR_QML_499 = qsTr("You received")
var STR_QML_500 = qsTr("You're receiving")
var STR_QML_501 = qsTr("Chat info")
var STR_QML_502 = qsTr("Please select chat room")
var STR_QML_503 = qsTr("Add members")
var STR_QML_504 = qsTr("Leave group")
var STR_QML_505 = qsTr("Pending transactions")
var STR_QML_506 = qsTr("Please plug in and unlock your device")
var STR_QML_507 = qsTr("Please sign using export and import transaction button.")
var STR_QML_508 = qsTr("This is a software key resided in another device")
var STR_QML_509 = qsTr("Sign")
var STR_QML_510 = qsTr("Rescan")
var STR_QML_511 = qsTr("Assigned")

var STR_QML_512 = qsTr("Edit profile")
var STR_QML_513 = qsTr("Display unit (BTC)")
var STR_QML_514 = qsTr("Network settings")
var STR_QML_515 = qsTr("Hardware driver")
var STR_QML_516 = qsTr("Change your password")
var STR_QML_517 = qsTr("Logged-in devices")
var STR_QML_518 = qsTr("About")
var STR_QML_519 = qsTr("Display unit")
var STR_QML_520 = qsTr("Show Fixed Precision")
var STR_QML_521 = qsTr("Network Settings")
var STR_QML_522 = qsTr("Connect to Electrum server")
var STR_QML_523 = qsTr("Path to Your SSL Certificate")
var STR_QML_524 = qsTr("Upload SSL file")
var STR_QML_525 = qsTr("Change password")
var STR_QML_526 = qsTr("Current password")
var STR_QML_527 = qsTr("Update password")
var STR_QML_528 = qsTr("Save network settings")
var STR_QML_529 = qsTr("Reset to default network settings")
var STR_QML_530 = qsTr("Database Encryption")
var STR_QML_531 = qsTr("Confirm passphrase doesn't match passphrase")
var STR_QML_532 = qsTr("Import PSBT")
var STR_QML_533 = qsTr("Sign in")
var STR_QML_534 = qsTr("Apply")
var STR_QML_535 = qsTr("Guest")
var STR_QML_536 = qsTr("Verifying")
var STR_QML_537 = qsTr("Account Settings")
var STR_QML_538 = qsTr("Add account")
var STR_QML_539 = qsTr("Delete account")
var STR_QML_540 = qsTr("Deleting your account is a permanent action")
var STR_QML_541 = qsTr("Adding your account is a permanent action")

var STR_QML_542 = qsTr("Are you sure you want to delete this account? Please type DELETE to confirm.")
var STR_QML_543 = qsTr("Confirm account deletion")
var STR_QML_544 = qsTr("We've sent a confirmation code to <b>%1.</b> Please enter the code below to confirm the deletion of this account")
var STR_QML_545 = qsTr("Your password has successfully been updated")
var STR_QML_546 = qsTr("Mark as compromised")
var STR_QML_547 = qsTr("Sign out of all devices")
var STR_QML_548 = qsTr("Signd out")
var STR_QML_549 = qsTr("Unknown")
var STR_QML_550 = qsTr("Your contact request has been sent")
var STR_QML_551 = qsTr("Your invitation has been sent")
var STR_QML_552 = qsTr("Text size must be more than or equal 5 characters")
var STR_QML_553 = qsTr("Taproot")

var STR_QML_554 = qsTr("Oops, your key is currently being used in a wallet. Please remove the wallet first.")
var STR_QML_555 = qsTr("Please remove this key on the device that it was added to.")

var STR_QML_556 = qsTr("Current wallet config")
var STR_QML_557 = qsTr("Not configured")
var STR_QML_558 = qsTr("Single-sig")
var STR_QML_559 = qsTr("%1/%2 multisig")
var STR_QML_560 = qsTr("Top up XPUBs")
var STR_QML_561 = qsTr("Placeholder default message")
var STR_QML_562 = qsTr("This is placeholder of signature automatically generated after export message")


var STR_QML_570 = qsTr("Spend from collaborative wallet")
var STR_QML_571 = qsTr("Please download and install the update from our website")
var STR_QML_572 = qsTr("I'll do this later")
var STR_QML_573 = qsTr("Update recommended")
var STR_QML_574 = qsTr("View wallet config")
var STR_QML_575 = qsTr("That does not look like a valid email address")

var STR_QML_576 = qsTr("Are you sure you want to sign out %1?")
var STR_QML_577 = qsTr("Are you sure you want to mark %1 as compromised? The device’s access to messages and wallets will be removed.")
var STR_QML_578 = qsTr("Are you sure you want to sign out all devices")

var STR_QML_579 = qsTr("%1 has been marked as compromised")
var STR_QML_580 = qsTr("All devices have been deleted")
var STR_QML_581 = qsTr("%1 has been deleted")

var STR_QML_582 = qsTr("Topping up XPUBs")
var STR_QML_583 = qsTr("Signet Server")
var STR_QML_584 = qsTr("Signet")
var STR_QML_585 = qsTr("Explorer address")

var STR_QML_586 = qsTr("Changes are saved")
var STR_QML_587 = qsTr("Please name your wallet")

var STR_QML_588 = qsTr("Developer settings")
var STR_QML_589 = qsTr("Enable debug mode")

var STR_QML_590 = qsTr("You might not be able to read encrypted messages from the original device. A Device Verification feature will allow you to do so in the feature. Follow us on Twitter for updates.")
var STR_QML_591 = qsTr("Type contact's email or username")
var STR_QML_592 = qsTr("Get started")
var STR_QML_593 = qsTr("Multi-device sync (experimental)")

var STR_QML_594 = qsTr("Nunchuk")
var STR_QML_595 = qsTr("Invalid delete account confirmation code")
var STR_QML_596 = qsTr("Ok")

var STR_QML_597 = qsTr("Guest mode")
var STR_QML_598 = qsTr("Guest mode allows you to create keys and wallets without an account. Please consider the following before using—")
var STR_QML_599 = qsTr("Keys and wallets created in guest mode are stored locally. They will not be removed until you manually delete them or uninstall the app.")
var STR_QML_600 = qsTr("Messaging and collaborative multisig wallets (*) are currently not available in guest mode.")
var STR_QML_601 = qsTr("*A collaborative multisig wallet is a wallet where you co-manage bitcoin with other people.")

var STR_QML_602 = qsTr("Send a message")

//SCR_RECOVER_SHARED_WALLET.qml
var STR_QML_603 = qsTr("Recover collaborative wallet")
var STR_QML_604 = qsTr("In order to recover a collaborative wallet, you will need:")
var STR_QML_605 = qsTr("Room members to recover the keys from the original wallet")
var STR_QML_606 = qsTr("A copy of the wallet configuration file (BSMS or descriptors)")
var STR_QML_607 = qsTr("Recover using BSMS/descriptors")
var STR_QML_608 = qsTr("Recover using QR code")

var STR_QML_609 = qsTr("Are you sure you want to delete this contact? This cannot be undone.")
var STR_QML_610 = qsTr("You currently have a collaborative wallet with this contact. Please remove the wallet before removing the contact.")

var STR_QML_611 = qsTr("Online")
var STR_QML_612 = qsTr("Offline")
var STR_QML_613 = qsTr("Syncing")

var STR_QML_614 = qsTr("Please add a key before adding a wallet")
var STR_QML_615 = qsTr("hardware, software and air-gapped keys are supported.")

var STR_QML_616 = qsTr("Looks like you have added a signer")
var STR_QML_617 = qsTr("Do you want to add a Bitcoin wallet?")

var STR_QML_618 = qsTr("Message function require an account")
var STR_QML_619 = qsTr("We use email as the user ID for shared wallet and interpersonal messaging features.")
var STR_QML_620 = qsTr("First and last name")

var STR_QML_621 = qsTr("Enter the confirmation code we sent to %1. <a href='dummycode.tbd'>Resend code</a>")

var STR_QML_622 = qsTr("Set your password")
var STR_QML_623 = qsTr("Your password must consist of 6 characters, at least 1 numer or symbol and atleast 1 letter.")
var STR_QML_624 = qsTr("Confirm password")

var STR_QML_625 = qsTr("You have no messages.")
var STR_QML_626 = qsTr("Send to")
var STR_QML_627 = qsTr("Do more with Nunchuk")
var STR_QML_628 = qsTr("Create an account or sign in to take advantage of our messenger and collaborative multisig wallet")

var STR_QML_629 = qsTr("Primary Key account")
var STR_QML_630 = qsTr("A Primary Key is a dual-purpose key that can be used both for account-based authentication and for signing Bitcoin transactions.")
var STR_QML_631 = qsTr("A Primary Key account is an account that does not require any personal information, including email addresses.")

var STR_QML_632 = qsTr("Sign in remotely via QR")
var STR_QML_633 = qsTr("Sign in manually")
var STR_QML_634 = qsTr("Import Primary Keys")

var STR_QML_635 = qsTr("Create an account using Primary Key")
var STR_QML_636 = qsTr("Add a Primary Key")
var STR_QML_637 = qsTr("Wired keys are supported. Support for air-gapped Primary Key coming soon.")

var STR_QML_638 = qsTr("Choose your username")
var STR_QML_639 = qsTr("The default username is the fingerprint (XFP) of your Primary Key. You can change this to something else.")
var STR_QML_640 = qsTr("Username")

var STR_QML_641 = qsTr("Primary Key")
var STR_QML_642 = qsTr("Are you sure you don’t want a passphrase? A Primary Key without a passphrase means that your account is unprotected. Anyone who has access to your device can access all your data, including your wallets.")
var STR_QML_643 = qsTr("Sign in using Primary Key")

var STR_QML_644 = qsTr("Please enter the seed phrase.")
var STR_QML_645 = qsTr("Passphrase")
var STR_QML_646 = qsTr("Please enter the passphrase associated with the Primary Key. If you don’t have one, leave it blank.")

var STR_QML_647 = qsTr("Your username")
var STR_QML_648 = qsTr("Challenge message")
var STR_QML_649 = qsTr("Your signature")
var STR_QML_650 = qsTr("Add Primary Key account")

var STR_QML_651 = qsTr("Copied to clipboard")
var STR_QML_652 = qsTr("Refresh")
var STR_QML_653 = qsTr("Primary Key accounts")
var STR_QML_654 = qsTr("For wired Primary Key account, please ensured the wired key is plugged in and unlocked")

var STR_QML_655 = qsTr("Add or sign in remotely")
var STR_QML_656 = qsTr("Primary Key name")

var STR_QML_657 = qsTr("Replace Primary Key")
var STR_QML_658 = qsTr("A Primary Key is a dual-purpose key that can be used both for account-based authentication and for signing Bitcoin transactions. Please note the following:")
var STR_QML_659 = qsTr("If you choose to proceed, your Primary Key will be replaced with a new one. Your current Primary Key will be downgraded to a regular key.")
var STR_QML_660 = qsTr("If you have assigned the current Primary Key to any wallets, those wallets will remain unchanged. You will need the existing key in order to sign transactions in those wallets. Please do not delete it if there is still a balance.")
var STR_QML_626_ = qsTr("Receive address")
var STR_QML_661 = qsTr("Warning")
var STR_QML_662 = qsTr("Deleting this collaborative wallet will also delete the corresponding chat. Are you sure you want to delete?")

var STR_QML_663 = qsTr("Could not change the passhrase for database")
var STR_QML_664 = qsTr("Change the passhrase for database successfully!")
var STR_QML_665 = qsTr("Passphrase adds another layer of security to your key. You will need to enter the passphrase every time you use this key. You can think of it as the 25th word of your seed phrase.")
var STR_QML_666 = qsTr("We strongly recommend adding a passphrase for your Primary Key.")

var STR_QML_667 = qsTr("Wrong passphrase")
var STR_QML_668 = qsTr("Copied to clipboard")
var STR_QML_669 = qsTr("Neither this account nor this key has a passphrase. Anyone who has access to your device can use this key to sign malicious transactions.")
var STR_QML_670 = qsTr("I understand the risk")
var STR_QML_671 = qsTr("Could not create account");

var STR_QML_672 = qsTr("Are you sure you want to delete this account? All your keys and wallets will be removed. Please make sure that you have backups.")
var STR_QML_673 = qsTr("Please type DELETE to confirm.")

var STR_QML_674 = qsTr("Export wallet to Bitbox")
var STR_QML_675 = qsTr("Encrypted")
var STR_QML_676 = qsTr("Select the key you want to add")
var STR_QML_677 = qsTr("Import via file")
var STR_QML_678 = qsTr("NFC")
var STR_QML_679 = qsTr("Assisted")
var STR_QML_680 = qsTr("Iron Hand")
var STR_QML_681 = qsTr("Honey Badger")
var STR_QML_682 = qsTr("Manage subscription")
var STR_QML_683 = qsTr("Take me to the website")
var STR_QML_684 = qsTr("Please manage your subscription through our website. Sign in and navigate to the Plan and Invoices page.")
var STR_QML_685 = qsTr("NFC")
var STR_QML_686 = qsTr("Force refresh (advanced)")
var STR_QML_687 = qsTr("Are you sure you want to sign this transaction")
var STR_QML_688 = qsTr("TAPSIGNER is currently supported on mobile only.")
var STR_QML_689 = qsTr("Are you sure you want to perform a force refresh? This process will clear this wallet’s existing data (including notes and pending transactions) and attempt to re-sync it with the blockchain.")
var STR_QML_690 = qsTr("The wallet has been refreshed")
var STR_QML_691 = qsTr("Copy transaction ID")
var STR_QML_692 = qsTr("You don't have any transaction yet")
var STR_QML_693 = qsTr("Couldn't determine how to open the file, opening its folder instead")
var STR_QML_694 = qsTr("Couldn't determine how to open the file or its folder.")
var STR_QML_695 = qsTr("Attachment file is invalid")
var STR_QML_696 = qsTr("Allow only one file")

var STR_QML_697 = qsTr("Emergency lockdown")
var STR_QML_698 = qsTr("Key recovery")
var STR_QML_699 = qsTr("Your subscription")
var STR_QML_700 = qsTr("Order new hardware")
var STR_QML_701 = qsTr("Support")
var STR_QML_702 = qsTr("Emergency")

var STR_QML_703 = qsTr("If you feel that there is an imminent threat or \n \
just want to disable wallet access temporarily, you can activate the emergency lockdown. \n \
Please note the following:")
var STR_QML_704 = qsTr("Once you have entered the lockdown, no one—including yourself—will be able to \n \
sign in to your account and access your wallet.")
var STR_QML_705 = qsTr("There is no way to end the lockdown early.")
var STR_QML_706 = qsTr("Access will be automatically re-enabled once the lockdown period ends.")
var STR_QML_707 = qsTr("Get additional wallets")
var STR_QML_708 = qsTr("Start key recovery")
var STR_QML_709 = qsTr("Re-enter your password")
var STR_QML_710 = qsTr("For security, please re-enter your password.")

var STR_QML_711 = qsTr("Select your lockdown period")
var STR_QML_712 = qsTr("Your access will be automatically re-enabled once the lockdown period ends.")

var STR_QML_716 = qsTr("Answer security question")
var STR_QML_717 = qsTr("What is your nickname when you were young?")
var STR_QML_718 = qsTr("Answer")
var STR_QML_719 = qsTr("Please answer the following question. Answer is case-sensitive.")
var STR_QML_720 = qsTr("Your account is now under lockdown")
var STR_QML_721 = qsTr("The lockdown will last <b>%1</b>.")

var STR_QML_722 = qsTr("If you lost a TAPSIGNER or the card malfunctions, this procedure will recover the \n \
TAPSIGNER’s private key using the encrypted backup from our server. Please note the \n \
following:")
var STR_QML_723 = qsTr("Once you have entered the lockdown, no one—including yourself—will \n \
be able to sign in to your account and access your wallet.")
var STR_QML_724 = qsTr("There is no way to end the lockdown early.")

var STR_QML_725 = qsTr("Enter Backup Password")
var STR_QML_726 = qsTr("Please enter the Backup Password for [<b>%1</b>] (card ID: <b>••%2</b>).")
var STR_QML_727 = qsTr("Backup Password")
var STR_QML_728 = qsTr("The key recovery procedure currently only supports TAPSIGNER.")
var STR_QML_729 = qsTr("Please select the TAPSIGNER you want to recover")
var STR_QML_730 = qsTr("TAPSIGNER recovered")
var STR_QML_731 = qsTr("Your TAPSIGNER’s private key has been successfully recovered and \n \
converted into a software key. Please note the following:")
var STR_QML_732 = qsTr("The software key is stored on this device")
var STR_QML_733 = qsTr("You can continue signing transactions using this software key")
var STR_QML_734 = qsTr("If you suspect that someone has gained possession of the key, we recommend that you roll \n \
over your balance to a new wallet.")
var STR_QML_735 = qsTr("You can order new hardware by using the referral links on our website. Sign in and navigate to the Hardware Replacement page.")
var STR_QML_736 = qsTr("Inheritance planning")
var STR_QML_737 = qsTr("Claim an inheritance")
var STR_QML_738 = qsTr("Platform key co-signing policies")
var STR_QML_739 = qsTr("TAPSIGNER has been recovered.")
var STR_QML_740 = qsTr("The password is printed on the back of the TAPSIGNER. You should have had a copy of this \n \
when setting up the TAPSIGNER for the first time.")
var STR_QML_741 = qsTr("Local currency (%1)")
var STR_QML_742 = qsTr("Local currency")
var STR_QML_743 = qsTr("Need support? Chat with an expert")
var STR_QML_744 = qsTr("You currently do not have any TAPSIGNER added.")
var STR_QML_745 = qsTr("Photos and videos")
var STR_QML_746 = qsTr("Upload file")

var STR_QML_747 = qsTr("Claim inheritance")
var STR_QML_748 = qsTr("Please enter the Magic Phrase and Backup Password")
var STR_QML_749 = qsTr("Magic Phrase")
var STR_QML_750 = qsTr("It looks like the original subscription has expired for more than 3 years. To claim the inheritance, please reactivate the plan first by visiting nunchuk.io/claim.")
var STR_QML_751 = qsTr("Take me to reactivate the plan")
var STR_QML_752 = qsTr("Your inheritance plan has not been activated yet. Please try again later.")
var STR_QML_753 = qsTr("Become a subscriber to get access to our services.")

var STR_QML_754 = qsTr("Get more out of Nunchuk with an assisted wallet")
var STR_QML_755 = qsTr("Here are some of the things that you can do with an assisted wallet:")
var STR_QML_756 = qsTr("No single point of failure")
var STR_QML_757 = qsTr("Eliminate single points of failure by using multisig: two keys are always required for spending. The loss of any one key will not compromise your funds.")
var STR_QML_759 = qsTr("Plan your inheritance in a non-custodial way and ensure that your bitcoins can be safely passed on to your loved ones. Compatible with existing estate plans.")
var STR_QML_762 = qsTr("Lock your wallet access when there is a security threat or when you go off the grid.")
var STR_QML_763 = qsTr("Flexible spending policies")
var STR_QML_764 = qsTr("Set up scheduled payments, extra security measures when withdrawing large amounts of bitcoins, and more.")
var STR_QML_765 = qsTr("Cloud backups and assisted recovery")
var STR_QML_766 = qsTr("Have peace of mind knowing that your wallet backups are encrypted and stored securely in the cloud. Assisted recovery is a breeze.")
var STR_QML_767 = qsTr("In-app chat support")
var STR_QML_768 = qsTr("Chat to an expert directly within the app when you run into issues.")
var STR_QML_770 = qsTr("Tell me more")

var STR_QML_771 = qsTr("Please start the claiming process by visiting nunchuk.io/claim.")
var STR_QML_772 = qsTr("Take me there")

var STR_QML_773 = qsTr("Buffer period has started")
var STR_QML_774 = qsTr("The owner of this plan set up a buffer period before the inheritance can be claimed.")
var STR_QML_774_ = qsTr("Please check back in <b>%1</b>.")
var STR_QML_775 = qsTr("Your inheritance")
var STR_QML_776 = qsTr("Congratulations! You have unlocked your inheritance")
var STR_QML_777 = qsTr("Done")
var STR_QML_778 = qsTr("Withdraw balance")
var STR_QML_779 = qsTr("Withdraw to a Nunchuk wallet")
var STR_QML_780 = qsTr("Withdraw to an address")
var STR_QML_781 = qsTr("You have a message below")

var STR_QML_782 = qsTr("Which wallet do you want to withdraw bitcoin to?")
var STR_QML_783 = qsTr("View on blockchain explorer")
var STR_QML_784 = qsTr("Confirm and withdraw balance")
var STR_QML_785 = qsTr("Transaction details")
var STR_QML_786 = qsTr("New transaction")
var STR_QML_787 = qsTr("Enter recipient’s address")

var STR_QML_788 = qsTr("Congratulations!")
var STR_QML_789 = qsTr("Your inheritance has been claimed.")
var STR_QML_790 = qsTr("Hardware key discounts")
var STR_QML_791 = qsTr("Get exclusive discounts when purchasing hardware signing devices from our partners.")
var STR_QML_792 = qsTr("Broadcast and delay")
var STR_QML_793 = qsTr("You can always bypass the co-signing delay by using your own keys.")
var STR_QML_794 = qsTr("Automatically broadcast transaction after co-signing")
var STR_QML_795 = qsTr("Enable co-signing delay")
var STR_QML_796 = qsTr("A co-signing delay gives you time to detect errors or unauthorized acccess before a transaction is broadcast.")
var STR_QML_797 = qsTr("Hours")
var STR_QML_798 = qsTr("Minutes")

var STR_QML_799 = qsTr("Spending limit")
var STR_QML_800 = qsTr("The platform key will only co-sign transactions if the total amount spent has not exceeded the spending limit.")
var STR_QML_801 = qsTr("Co-signing spending limit")
var STR_QML_802 = qsTr("Broadcast and delay")
var STR_QML_803 = qsTr("Platform key co-signing policies")
var STR_QML_804 = qsTr("Continue to save changes")
var STR_QML_805 = qsTr("Discard changes")
var STR_QML_806 = qsTr("Increasing the co-signing spending limit requires signing a dummy transaction. Please do so via the mobile app.")
var STR_QML_807 = qsTr("The estimated fee is calculated using current market conditions. You can set your own fee by toggling the customize fee setting.")
var STR_QML_808 = qsTr("Please set a delay that is less than 168 hours.")
var STR_QML_809 = qsTr("Transactions with fee too low might get kicked out of the mempool. Are you sure you want to continue?")

var STR_QML_810 = qsTr("Add Ledger to your assisted wallet")
var STR_QML_811 = qsTr("Add Ledger")
var STR_QML_812 = qsTr("It looks like you want to add Ledger as a hardware key to an assisted wallet. Would you like to do it now?")

var STR_QML_813 = qsTr("Add Trezor to your assisted wallet")
var STR_QML_814 = qsTr("Add Trezor")
var STR_QML_815 = qsTr("It looks like you want to add Trezor as a hardware key to an assisted wallet. Would you like to do it now?")

var STR_QML_816 = qsTr("Insufficient funds")
var STR_QML_817 = qsTr("Please ensure to do the following before proceeding.")
var STR_QML_818 = qsTr("Initialize the device key")
var STR_QML_819 = qsTr("Follow Ledger’s instruction on how to set up your device with a seed phrase.")
var STR_QML_820 = qsTr("To unlock the device, you might need to enter a PIN and/or a PASSPHRASE directly on the device screen.")

var STR_QML_821 = qsTr("Install the Bitcoin app")
var STR_QML_822 = qsTr("If you haven’t already, install the Bitcoin (BTC) app on the Ledger device. Please refer to Ledger’s guide.")

var STR_QML_824 = qsTr("Please ensure that the Ledger device is connected to this computer, and click on Refresh")
var STR_QML_825 = qsTr("Configure gap limit (advanced)")
var STR_QML_826 = qsTr("Adding Ledger...")

var STR_QML_827 = qsTr("Ledger added successfully")
var STR_QML_828 = qsTr("To finish setting up your assisted wallet, please return to your mobile device.")

var STR_QML_829 = qsTr("Follow Trezor’s instruction on how to set up your device with a seed phrase.")
var STR_QML_830 = qsTr("Please ensure that the Trezor device is connected to this computer, and click on Refresh")
var STR_QML_831 = qsTr("Adding Trezor...")
var STR_QML_832 = qsTr("Trezor added successfully")
var STR_QML_833 = qsTr("Gap limit has been updated")
var STR_QML_834 = qsTr("Gap limit cannot exceed 100.")

var STR_QML_835 = qsTr("Save")
var STR_QML_836 = qsTr("Effective package fee rate: %1 sat/vB")
var STR_QML_837 = qsTr("Select an assisted wallet")
var STR_QML_838 = qsTr("Which wallet do you want to select?")

var STR_QML_839 = qsTr("This feature is only available with an assisted wallet. Please create one first.")
