/**************************************************************************
 * This file is part of the Nunchuk software (https://nunchuk.io/)        *
 * Copyright (C) 2020-2022 Enigmo								          *
 * Copyright (C) 2022 Nunchuk								              *
 *                                                                        *
 * This program is free software; you can redistribute it and/or          *
 * modify it under the terms of the GNU General Public License            *
 * as published by the Free Software Foundation; either version 3         *
 * of the License, or (at your option) any later version.                 *
 *                                                                        *
 * This program is distributed in the hope that it will be useful,        *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 * GNU General Public License for more details.                           *
 *                                                                        *
 * You should have received a copy of the GNU General Public License      *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.  *
 *                                                                        *
 **************************************************************************/
.pragma library
// COMMON


// SCR_HOME.qml
var STR_QML_000 = qsTr("Wallets")
var STR_QML_001 = qsTr("Wallet details")
var STR_QML_002 = qsTr("Send")
var STR_QML_003 = qsTr("Receive")
var STR_QML_004 = qsTr("Quick receive")
var STR_QML_005  = qsTr("Copy")
var STR_QML_006 = qsTr("Verify on device")
var STR_QML_007 = qsTr("Check the correctness of this address on your device. Make sure your device is connected and unlocked.")
var STR_QML_008 = qsTr("Please check the address on your device")
var STR_QML_009 = qsTr("Member keys (%1 of %2)")
var STR_QML_010 = qsTr("Recent transactions")
var STR_QML_010_number = qsTr("(%1 total)")
var STR_QML_011 = qsTr("View all transactions")
var STR_QML_012 = qsTr("Mainnet")
var STR_QML_013 = qsTr("Testnet")
var STR_QML_014 = qsTr("Sample wallet")
var STR_QML_015 = qsTr("Keys")
var STR_QML_016 = qsTr("Sample key")
var STR_QML_017 = qsTr("Fee rates")
var STR_QML_018 = qsTr("High priority")
var STR_QML_019 = qsTr("Medium priority")
var STR_QML_020 = qsTr("Low priority")

// SCR_ADD_WALLET.qml
var STR_QML_021 = qsTr("Add new wallet")
var STR_QML_022 = qsTr("Wallet configuration")
var STR_QML_023 = qsTr("Key configuration")
var STR_QML_024 = qsTr("Confirmation")
var STR_QML_025 = qsTr("Wallet name")
var STR_QML_026 = qsTr("Wallet description")
var STR_QML_027 = qsTr("Wallet type")
var STR_QML_028 = qsTr("Standard wallet")
var STR_QML_029 = qsTr("One-time Escrow Wallet")
var STR_QML_030 = qsTr("An Escrow Wallet is a special single-use wallet, designed to hold funds temporarily.")
var STR_QML_031 = qsTr("Advanced: Address Type (Default: Native Segwit)")
var STR_QML_032 = qsTr("Native Segwit (highest fee saving)")
var STR_QML_033 = qsTr("Nested Segwit (medium fee saving)")
var STR_QML_034 = qsTr("Legacy (no fee saving)")
var STR_QML_035 = qsTr("Cancel")
var STR_QML_036 = qsTr("Import Wallet")
var STR_QML_037 = qsTr("Recover via BSMS/descriptors/config file")
var STR_QML_038 = qsTr("Recover via QR code")
var STR_QML_039 = qsTr("Import QR Passport")
var STR_QML_040 = qsTr("Recover from COLDCARD")
var STR_QML_041 = qsTr("Import DB")
var STR_QML_042 = qsTr("NEXT: Key Setup")

//SCR_ADD_WALLET_SIGNER_CONFIGURATION.qml
var STR_QML_043 = qsTr("Choose from existing keys")
var STR_QML_044 = qsTr("Hardware")
var STR_QML_045 = qsTr("Air-gapped")
var STR_QML_046 = qsTr("Software")
var STR_QML_047 = qsTr("Foreign")
var STR_QML_048 = qsTr("Assign to wallet")
var STR_QML_049 = qsTr("Or Add a New Key")
var STR_QML_050 = qsTr("Add new key")
var STR_QML_051 = qsTr("Air-gapped keys supported")
var STR_QML_052 = qsTr("Key configuration")
var STR_QML_053 = qsTr("NUMBER OF KEYS:")
var STR_QML_054 = qsTr("(Maximum 15)")
var STR_QML_055 = qsTr("BIP32 Path: %1")
var STR_QML_056 = qsTr("Required signers:")
var STR_QML_057 = qsTr("of")
var STR_QML_058 = qsTr("Number of Signatures Required to Unlock Funds")
var STR_QML_059 = qsTr("Back")
var STR_QML_060 = qsTr("Next: Review Wallet")

//SCR_ADD_WALLET_CONFIRMATION.qml
var STR_QML_061 = qsTr("Wallet & Key Configuration")
var STR_QML_062 = qsTr("Native Segwit")
var STR_QML_063 = qsTr("Nested Segwit")
var STR_QML_064 = qsTr("Legacy")
var STR_QML_065 = qsTr("Random")
var STR_QML_066 = qsTr("Address type")
var STR_QML_067 = qsTr("CREATED")
var STR_QML_068 = qsTr("Key configuration")
var STR_QML_069 = qsTr("Multisig")
var STR_QML_070 = qsTr("Single-sig")
var STR_QML_071 = qsTr("Get XPUBs")
var STR_QML_072 = qsTr("To create new wallets, additional XPUBs from the key are needed. Please plug in your key device, unlock, and press \"Get XPUBs\"")
var STR_QML_073 = qsTr("Create Wallet")
var STR_QML_074 = qsTr("Get XPUBs for key: ")
var STR_QML_075 = qsTr("Nunchuk is processing your key information")
var STR_QML_076 = qsTr("Creating new wallet")
var STR_QML_077 = qsTr("Please save the wallet configuration file (.bsms). You can use it to recover your wallet later using any BSMS-compatible software. BSMS is defined in BIP-0129: Bitcoin Secure Multisig Setup.")
var STR_QML_078 = qsTr("Save BSMS File")
var STR_QML_079 = qsTr("I'll do this later")
var STR_QML_080 = qsTr("*Note that this backup strictly contains information about the wallet. It does not include information on seeds or private keys.")
var STR_QML_081 = qsTr("Your wallet is almost ready")
var STR_QML_082 = qsTr("Wrapping up...")

//SCR_ADD_NEW_SIGNER.qml
var STR_QML_083 = qsTr("Add a key")
var STR_QML_084 = qsTr("Hardware key")
var STR_QML_085 = qsTr("Wired and air-gapped keys supported.")
var STR_QML_086 = qsTr("Add hardware key")
var STR_QML_087 = qsTr("Software key")
var STR_QML_088 = qsTr("The software key will be stored locally on this device.")
var STR_QML_089 = qsTr("Add software key")
var STR_QML_090 = qsTr("Already added")
var STR_QML_091 = qsTr("Before you start")
var STR_QML_092 = qsTr("Please ensure to do the following before proceeding")
var STR_QML_093 = qsTr("Initialize the device key")
var STR_QML_094 = qsTr("Follow the vendor's instruction on how to set up your device with a seed phrase.")
var STR_QML_095 = qsTr("Unlock the device")
var STR_QML_096 = qsTr("To unlock the device, you might need to enter a <b>PIN</b> and/or a <b>PASSPHRASE</b> directly on the device screen.")
var STR_QML_097 = qsTr("Continue")
var STR_QML_098 = qsTr("A software key will be generated locally on this device. <b>Deleting the app will also delete the software key.</b> Please make sure to:")
var STR_QML_099 = qsTr("Recover existing key")
var STR_QML_100 = qsTr("Create new key")

//SCR_ADD_HARDWARE_SIGNER.qml
var STR_QML_101 = qsTr("Add a hardware key")
var STR_QML_102 = qsTr("Key name")
var STR_QML_103 = qsTr("Add a wired key")
var STR_QML_104 = qsTr("Added")
var STR_QML_105 = qsTr("Refresh devices")
var STR_QML_106 = qsTr("Add key")
var STR_QML_107 = qsTr("Add an air-gapped key")
var STR_QML_108 = qsTr("Please enter your air-gapped key’s spec in the output descriptor format.")
var STR_QML_109 = qsTr("XPUB")
var STR_QML_110 = qsTr("The data inputted is not valid")
var STR_QML_111 = qsTr("BIP32 Path")
var STR_QML_112 = qsTr("Master Key Fingerprint")
var STR_QML_113 = qsTr("Via QR Code")
var STR_QML_114 = qsTr("Export via QR")
var STR_QML_117 = qsTr("Nunchuk is connecting to your device.")
var STR_QML_118 = qsTr("Key Health Check")
var STR_QML_119 = qsTr("Test signing message. Please wait and confirm the action on your key device.")
var STR_QML_120 = qsTr("Processing ...")
var STR_QML_121 = qsTr("Creating key: ")
var STR_QML_122 = qsTr("Please wait ...")
var STR_QML_123 = qsTr("XPUB or Public Key")
var STR_QML_124 = qsTr("You can also enter the Public Key if used for Escrow Wallets")
var STR_QML_125 = qsTr("OR")

//SCR_ADD_MASTER_SIGNER_RESULT.qml
var STR_QML_126 = qsTr("Key info")
var STR_QML_127 = qsTr("Key spec")
var STR_QML_128 = qsTr("Used in wallets")
var STR_QML_129 = qsTr("Health check")
var STR_QML_130 = qsTr("Custom test message")
var STR_QML_131 = qsTr("Message to sign")
var STR_QML_132 = qsTr("Signature")
var STR_QML_133 = qsTr("Health Check Result Details...")
var STR_QML_135 = qsTr("No signature generated. Please check your connection and make sure you have unlocked the device.")
var STR_QML_136 = qsTr("Plug in your key to perform a health check.")
var STR_QML_137 = qsTr("Run health check")
var STR_QML_138 = qsTr("Confirm & Close")
var STR_QML_139 = qsTr("Close")
var STR_QML_140 = qsTr("Please sign this message on your device")
var STR_QML_141 = qsTr("Please Confirm on the Key Device")

//SCR_ADD_NEW_SOFTWARE_SIGNER.qml
var STR_QML_142 = qsTr("Seed phrase")
var STR_QML_143 = qsTr("Please take a moment to write down this seed phrase. It’s the backup for your key. <b>This app will only show the seed phrase once.</b>")
var STR_QML_144 = qsTr("Never share the recovery phrase with anyone. Avoid having a digital copy.")

//SCR_ADD_REMOTE_SIGNER_RESULT.qml
var STR_QML_145 = qsTr("Key Info (Air-Gapped)")
var STR_QML_146 = qsTr("The Key has been added successfully!")
var STR_QML_147 = qsTr("Air-gapped key spec")
var STR_QML_148 = qsTr("Public Key:")
var STR_QML_149 = qsTr("XPUB:")
var STR_QML_150 = qsTr("BIP32 Path:")
var STR_QML_151 = qsTr("Master Key Fingerprint:")
var STR_QML_152 = qsTr("EXPORT MESSAGE")
var STR_QML_153 = qsTr("IMPORT MESSAGE")
var STR_QML_154 = qsTr("Health Check Result")
var STR_QML_155 = qsTr("%1 is healthy")
var STR_QML_156 = qsTr("That doesn't seem right. Please double check the signature.")

//SCR_APP_SETTINGS.qml
var STR_QML_157 = qsTr("Settings")
var STR_QML_158 = qsTr("Display unit")
var STR_QML_159 = qsTr("Show fixed precision")
var STR_QML_160 = qsTr("satoshi (1 BTC = 100,000,000 sat)")
var STR_QML_161 = qsTr("Database encryption")
var STR_QML_162 = qsTr("Enter passphrase")
var STR_QML_163 = qsTr("Passphrase must have at least 8 characters.")
var STR_QML_164 = qsTr("Passphrase changed successfully.")
var STR_QML_165 = qsTr("Could not change your passphrase")
var STR_QML_166 = qsTr("Re-enter to confirm passphrase")
var STR_QML_167 = qsTr("Change passphrase")
var STR_QML_168 = qsTr("Custom HWI Driver")
var STR_QML_169 = qsTr("Enter Path to Your HWI Executable")
var STR_QML_170 = qsTr("Network settings")
var STR_QML_171 = qsTr("Connect to Electrum server")
var STR_QML_172 = qsTr("Connect to Core node")
var STR_QML_173 = qsTr("Mainnet Server")
var STR_QML_174 = qsTr("Testnet Server")
var STR_QML_175 = qsTr("Set SSL certificate")
var STR_QML_176 = qsTr("Enter Path to Your SSL Certificate")
var STR_QML_177 = qsTr("Enable TOR proxy")
var STR_QML_178 = qsTr("Proxy address")
var STR_QML_179 = qsTr("Port")
var STR_QML_180 = qsTr("Proxy name")
var STR_QML_181 = qsTr("Proxy password")
var STR_QML_182 = qsTr("If you switch to Core for the first time and your wallet has a history, a blockchain rescan would be needed to reconstruct the wallet. This process might take some time.")
var STR_QML_183 = qsTr("RPC host")
var STR_QML_184 = qsTr("RPC Port")
var STR_QML_185 = qsTr("RPC username")
var STR_QML_186 = qsTr("RPC password")
var STR_QML_187 = qsTr("Manual rescan")
var STR_QML_188 = qsTr("Block height")
var STR_QML_189 = qsTr("Rescan")
var STR_QML_190 = qsTr("Please wait, processing ...")
var STR_QML_191 = qsTr("Apply changes?")
var STR_QML_192 = qsTr("Please note that some changes require an app reboot.")
var STR_QML_193 = qsTr("Discard changes")
var STR_QML_194 = qsTr("Apply")
var STR_QML_195 = qsTr("Restart application")
var STR_QML_196 = qsTr("Please restart the application to apply the new settings.")
var STR_QML_197 = qsTr("Restart")

//SCR_CHANGE_ADDRESS.qml
var STR_QML_198 = qsTr("Change addresses")
var STR_QML_199 = qsTr("Unused address (%1)")
var STR_QML_200 = qsTr("Used address (%1)")
var STR_QML_201 = qsTr("An address is marked as used as soon as money is deposited into it. For better privacy, reusing addresses is not recommended.")
var STR_QML_202 = qsTr("Generate new address")
var STR_QML_203 = qsTr("UNUSED")
var STR_QML_204 = qsTr("USED")
var STR_QML_205 = qsTr("Copy address")

//SCR_CREATE_NEW_SEED.qml
var STR_QML_206 = qsTr("Confirm seed")
var STR_QML_207 = qsTr("Please confirm the following words.")
var STR_QML_208 = qsTr("Confirm seed fail")

//SCR_CREATE_TRANSACTION.qml
var STR_QML_209 = qsTr("Replace-by-fee")
var STR_QML_210 = qsTr("Consolidate outputs")
var STR_QML_211 = qsTr("Confirm transaction")
var STR_QML_212 = qsTr("Escrow")
var STR_QML_213 = qsTr("Send to address")
var STR_QML_214 = qsTr("Amount")
var STR_QML_215 = qsTr("Estimated fee")
var STR_QML_216 = qsTr("Total amount")
var STR_QML_217 = qsTr("Change address")
var STR_QML_218 = qsTr("Transaction note")
var STR_QML_219 = qsTr("Signatures")
var STR_QML_220_S = qsTr("Pending 1 signature")
var STR_QML_220_M = qsTr("Pending %1 signatures")

function str_QML_220(m) {
    return m === 1 ? STR_QML_220_S : STR_QML_220_M.arg(m)
}

var STR_QML_221 = qsTr("Manual coin selection")
var STR_QML_222 = qsTr("Output address")
var STR_QML_223 = qsTr("CONF.")
var STR_QML_224 = qsTr("AMT")
var STR_QML_225 = qsTr("Customize fee setting")
var STR_QML_226 = qsTr("Subtract fee from send amount")
var STR_QML_227 = qsTr("The fee will be deducted from the amount being sent. The recipient will receive less bitcoins than you enter in the amount field.")
var STR_QML_228 = qsTr("Manual fee rate")
var STR_QML_229 = qsTr("You may bump the fee rate later using Replace By Fee.")
var STR_QML_230 = qsTr("The new fee rate needs to be higher than %1.")
var STR_QML_231 = qsTr("the original fee (%1)")
var STR_QML_232 = qsTr("Priority rate:")
var STR_QML_233 = qsTr("Standard rate:")
var STR_QML_234 = qsTr("Economical rate:")
var STR_QML_235 = qsTr("Confirm and create transaction")
var STR_QML_236 = qsTr("Creating transaction")

//SCR_LOGIN_ONLINE.qml
var STR_QML_237 = qsTr("Please enter your passphrase")
var STR_QML_238 = qsTr("The passphrase you entered is incorrect.")
var STR_QML_239 = qsTr("Enter The Dragon")

//SCR_MASTER_SIGNER_INFO.qml
var STR_QML_240 = qsTr("Key info")
var STR_QML_241 = qsTr("Remove key")
var STR_QML_242 = qsTr("Confirmation")
var STR_QML_243 = qsTr("Are you sure you want to remove this key?")
var STR_QML_243_used = qsTr("This key is currently being used in a wallet. Are you sure you want to delete it?")
var STR_QML_244 = qsTr("Type \"DELETE\" to confirm deletion.")
var STR_QML_245 = qsTr("Cancel")
var STR_QML_246 = qsTr("Delete")

//SCR_RECEIVE.qml
var STR_QML_247 = qsTr("Receive funds")
var STR_QML_248 = qsTr("Save as quick receive")
var STR_QML_249 = qsTr("Address balance:")

//SCR_RECOVER_SOFTWARE_SIGNER.qml
var STR_QML_250 = qsTr("Recover key via seed")
var STR_QML_251 = qsTr("Please enter the seed phrase.")
var STR_QML_252 = qsTr("Import signature")
var STR_QML_253 = qsTr("That doesn't seem right. Please double check your signature.")
var STR_QML_254 = qsTr("Make sure this key is no longer used in your wallets")
var STR_QML_255 = qsTr("Deleting this key can affect the wallets that are using it")

//SCR_REMOTE_SIGNER_INFO.qml
var STR_QML_256 = qsTr("Send funds")
var STR_QML_257 = qsTr("Create transaction")
var STR_QML_258 = qsTr("Batched transaction (advanced)")
var STR_QML_259 = qsTr("Balance")
var STR_QML_260 = qsTr("To address")
var STR_QML_261 = qsTr("Amount")
var STR_QML_262 = qsTr("Send all")
var STR_QML_263 = qsTr("Add recipient")
var STR_QML_264 = qsTr("Transaction note")
var STR_QML_265 = qsTr("Continue")

//SCR_SOFTWARE_SIGNER_CONFIGURATION.qml
var STR_QML_266 = qsTr("Give your key a name")
var STR_QML_267 = qsTr("Key name")
var STR_QML_268 = qsTr("Set a passphrase (optional)")
var STR_QML_268_PKEY = qsTr("Set a passphrase")
var STR_QML_269 = qsTr("Passphrase adds another layer of security to your key. You will need to enter the passphrase every time you sign using this key. You can think of it as the 25th word of your seed phrase. Passphrase is optional.")
var STR_QML_270 = qsTr("<b>Passphrase</b>")
var STR_QML_271 = qsTr("Confirm passphrase")
var STR_QML_272 = qsTr("Please back up your passphrase along with the seed. You will need both to recover your key.")
var STR_QML_273 = qsTr("Set passphrase")
var STR_QML_274 = qsTr("The confirm passphrase doesn't match")
var STR_QML_275 = qsTr("I don't need a passphrase")
var STR_QML_276 = qsTr("Processing...")
var STR_QML_277 = qsTr("The key is being added. Once complete, you can assign this key to new wallets.")

//SCR_TRANSACTION_HISTORY.qml
var STR_QML_278 = qsTr("Wallet info")
var STR_QML_279 = qsTr("Status")
var STR_QML_280 = qsTr("Transaction memo")
var STR_QML_281 = qsTr("Transaction data")

//SCR_TRANSACTION_INFO.qml
var STR_QML_282 = qsTr("Transaction info")
var STR_QML_283 = qsTr("Pending signatures")
var STR_QML_284 = qsTr("Ready to broadcast")
var STR_QML_285 = qsTr("Network rejected")
var STR_QML_286 = qsTr("Pending confirmations")
var STR_QML_287 = qsTr("Confirmations")
var STR_QML_288 = qsTr("Replaced by Fee")
var STR_QML_289 = qsTr("Member keys")
var STR_QML_290 = qsTr("Receive address")
var STR_QML_291 = qsTr("View on blockchain explorer")
var STR_QML_292 = qsTr("Remove transaction")
var STR_QML_293 = qsTr("Replace-by-fee")
var STR_QML_294 = qsTr("Export transaction")
var STR_QML_295 = qsTr("Start broadcasting")
var STR_QML_296 = qsTr("Cancel transaction")
var STR_QML_297 = qsTr("Signing transaction")
var STR_QML_298 = qsTr("Please confirm to sign on the key device")
var STR_QML_299 = qsTr("Export/Import transaction")
var STR_QML_300 = qsTr("Export PSBT")
var STR_QML_301 = qsTr("Import PSBT")
var STR_QML_302 = qsTr("Import via QR")
var STR_QML_303 = qsTr("Import from Passport/SeedSigner")

//SCR_UTXO_CONSOLIDATE.qml
var STR_QML_304 = qsTr("Consolidate outputs")
var STR_QML_305 = qsTr("Selected total:")

//SCR_UTXO_INFO.qml
var STR_QML_306 = qsTr("Unspent Output Info")
var STR_QML_307 = qsTr("VOUT")
var STR_QML_308 = qsTr("TRANSACTION ID")
var STR_QML_309 = qsTr("ADDRESS")
var STR_QML_310 = qsTr("SCRIPTPUBKEY")
var STR_QML_311 = qsTr("RELATED TRANSACTION")

//SCR_UTXOS.qml
var STR_QML_312 = qsTr("Unspent Outputs")
var STR_QML_313 = qsTr("UNSPENT OUTPUT")
var STR_QML_314 = qsTr("CONFIRMATIONS")
var STR_QML_315 = qsTr("UTXO Data")

//SCR_WALLET_INFO.qml
var STR_QML_316 = qsTr("Coldcard requires a multisig configuration file before it can sign transactions. Please choose \"Export\" > \"Export To Coldcard\", then copy the resulting file over to Coldcard.")
var STR_QML_317 = qsTr("Wallet name")
var STR_QML_318 = qsTr("Wallet description")
var STR_QML_319 = qsTr("Wallet type")
var STR_QML_320 = qsTr("Keys:")
var STR_QML_321 = qsTr("XFP:")
var STR_QML_322 = qsTr("Last heath check:")
var STR_QML_323 = qsTr("Export")
var STR_QML_324 = qsTr("Export Wallet BSMS File")
var STR_QML_325 = qsTr("Export Wallet Database")
var STR_QML_326 = qsTr("Export Transaction History (CSV)")
var STR_QML_327 = qsTr("Export UTXOs (CSV)")
var STR_QML_328 = qsTr("Export wallet to Coldcard")
var STR_QML_329 = qsTr("Export as QR code")
var STR_QML_331 = qsTr("More options")
var STR_QML_332 = qsTr("Delete wallet")
var STR_QML_333 = qsTr("*Export data do not include seeds or private keys.")
var STR_QML_334 = qsTr("Confirmation")
var STR_QML_335 = qsTr("Once you delete the wallet, all your data (and metadata such as transaction private notes) will be gone. We recommend backing up the wallet descriptors or database, if you want to recover the wallet later.")

//SCR_ASSIGN_SIGNER_TO_SHARED_WALLET.qml
var STR_QML_336 = qsTr("Assign key")
var STR_QML_337 = qsTr("Assign at least 1 key to the wallet")
var STR_QML_338 = qsTr(" slot left in the wallet")
var STR_QML_339 = qsTr("Info")
var STR_QML_340 = qsTr("You have exceeded your signer limit for this wallet. All members in the group must participate in the wallet.")
var STR_QML_341 = qsTr("Got it")

//SCR_BACKUP_SHARED_WALLET.qml
var STR_QML_342 = qsTr("Backup")
var STR_QML_343 = qsTr("Please save your wallet configuration")
var STR_QML_344 = qsTr("Losing the wallet configuration file alone does not compromise your funds, but you should still keep it safe to protect your privacy, as whoever has the configuration can monitor transactions in the wallet.")
var STR_QML_345 = qsTr("Tip: you need both the keys and the configuration to perform a wallet recovery.")
var STR_QML_346 = qsTr("I'll do this later")
var STR_QML_347 = qsTr("Export wallet configuration")

//SCR_CONFIGURE_SHARED_WALLET.qml
var STR_QML_348 = qsTr("Configure collaborative wallet")
var STR_QML_349 = qsTr("Total number of signers")
var STR_QML_350 = qsTr("Total number of signers in the wallet")
var STR_QML_351 = qsTr("Required signers")
var STR_QML_352 = qsTr("Number of signatures required to unlock funds")
var STR_QML_353 = qsTr("Current wallet config")

//SCR_CONTACT_PENDING_REQUEST.qml
var STR_QML_354 = qsTr("Pending requests")
var STR_QML_355 = qsTr("Received")
var STR_QML_356 = qsTr("Sent")

//SCR_CREATE_SHARED_WALLET.qml
var STR_QML_357 = qsTr("Create collaborative wallet")
var STR_QML_358 = qsTr("Customize wallet type")
var STR_QML_359 = qsTr("Defaut: Native Segwit")
var STR_QML_360 = qsTr("Highest fee saving")
var STR_QML_361 = qsTr("Medium fee saving")
var STR_QML_362 = qsTr("No fee saving")
var STR_QML_363 = qsTr("Customize address type")
var STR_QML_364 = qsTr("Defaut: Standard wallet")
var STR_QML_365 = qsTr("A special single-use wallet, designed to hold funds temporarily.")

//SCR_HOME_ONLINE.qml
var STR_QML_366 = qsTr("Messages")
var STR_QML_367 = qsTr("Direct messages")
var STR_QML_368 = qsTr("To create a collaborative wallet, please add your contacts then start a conversation.")
var STR_QML_369 = qsTr("Add Contact")
var STR_QML_370 = qsTr("Contacts")
var STR_QML_371 = qsTr("Pending requests")
var STR_QML_372 = qsTr("See all")
var STR_QML_373 = qsTr("Contact list")
var STR_QML_374 = qsTr("Delete contact")
var STR_QML_375 = qsTr("You have no contacts yet.")
var STR_QML_376 = qsTr("Completed")
var STR_QML_377 = qsTr("Pending finalization")
var STR_QML_378 = qsTr("Pending keys")
var STR_QML_379 = qsTr("Welcome to messages")
var STR_QML_380 = qsTr("Let’s begin by getting you some friends")
var STR_QML_381 = qsTr("Edit group name")
var STR_QML_382 = qsTr("Group name")
var STR_QML_383 = qsTr("Save group name")
var STR_QML_384 = qsTr("Add people")
var STR_QML_385 = qsTr("Enter a name or email")
var STR_QML_386 = qsTr("Add member")
var STR_QML_387 = qsTr("Please wait while the app is syncing ...")
var STR_QML_388 = qsTr("Data merge in progress ...")
var STR_QML_389 = qsTr("Please allow a moment for data to complete merging.")

//SCR_LOGIN_ONLINE.qml
var STR_QML_390 = qsTr("Welcome to Nunchuk")
var STR_QML_391 = qsTr("The gold standard of Bitcoin custody.")
var STR_QML_392 = qsTr("Create a new account")
var STR_QML_393 = qsTr("Your name")
var STR_QML_394 = qsTr("Email address")
var STR_QML_395 = qsTr("Create an account")
var STR_QML_396 = qsTr("This field is required")
var STR_QML_397 = qsTr("Back to previous")
var STR_QML_398 = qsTr("By creating an account, you agree to our <a href='%1'>Terms and Conditions</a> and <a href='%2'>Privacy Policy</a>")
var STR_QML_399 = qsTr("Can't create account")
var STR_QML_400 = qsTr("We’ve sent a temporary password to %1. Please change your password.")
var STR_QML_401 = qsTr("Temporary password")
var STR_QML_402 = qsTr("New password")
var STR_QML_403 = qsTr("Confirm new password")
var STR_QML_404 = qsTr("The password confirmation does not match.")
var STR_QML_405 = qsTr("Change password")
var STR_QML_406 = qsTr("New password must be different from the old password")
var STR_QML_407 = qsTr("Can't change password")
var STR_QML_408 = qsTr("Reset password")
var STR_QML_409 = qsTr("Enter the email address you used to register with Nunchuk and we'll send you a temporary password for you to sign in.")
var STR_QML_410 = qsTr("Send a new temporary password")
var STR_QML_411 = qsTr("Can't send request")
var STR_QML_412 = qsTr("We’ve sent a temporary password to %1. Please use it to change your password.")
var STR_QML_413 = qsTr("Temporary password")
var STR_QML_414 = qsTr("Can't reset password")
var STR_QML_415 = qsTr("Sign in to continue")
var STR_QML_416 = qsTr("Password")
var STR_QML_417 = qsTr("Stay signed in")
var STR_QML_418 = qsTr("Forgot password?")
var STR_QML_419 = qsTr("Sign in")
var STR_QML_420 = qsTr("Continue as guest")
var STR_QML_421 = qsTr("By creating an account or continuing as guest, you agree to our <a href='%1'>Terms and Conditions</a> and <a href='%2'>Privacy Policy</a>")
var STR_QML_422 = qsTr("We use email as the user ID for collaborative wallet and interpersonal messaging features. For stand-alone wallet that doesn’t require email sign up, please use guest mode.")
var STR_QML_423 = qsTr("Account does not exist")
var STR_QML_424 = qsTr("Enter confirmation code")
var STR_QML_425 = qsTr("Enter the confirmation code we sent to your email. <a href='dummycode.tbd'>Resend code</a>")
var STR_QML_426 = qsTr("Confirmation code")
var STR_QML_427 = qsTr("Confirm")

//SCR_ONLINE_ADD_CONTACTS.qml
var STR_QML_428 = qsTr("Add contacts")
var STR_QML_429 = qsTr("Enter emails or usernames, separated by spaces")
var STR_QML_430 = qsTr("Send invitation")
var STR_QML_431 = qsTr("These contacts are not on Nunchuk. Would you like to send an invite?")
var STR_QML_432 = qsTr("No")
var STR_QML_433 = qsTr("Yes")

//SCR_REVIEW_SHARED_WALLET.qml
var STR_QML_434 = qsTr("Review collaborative wallet")
var STR_QML_435 = qsTr("Wallet configuration")
var STR_QML_436 = qsTr("Address type")

//SCR_SHARED_WALLET_CONFIGURE.qml
var STR_QML_437 = qsTr("Wallet config")
var STR_QML_438 = qsTr("Collab")
var STR_QML_439 = qsTr("All keys have been assigned")
var STR_QML_440 = qsTr("Pending %1 keys to be assigned")
var STR_QML_440_ = qsTr("Pending 1 key to be assigned")
var STR_QML_441 = qsTr("Cancel wallet")
var STR_QML_442 = qsTr("Finalize wallet")
var STR_QML_443 = qsTr("Continue to assign signers")
var STR_QML_444 = qsTr("More options")
var STR_QML_445 = qsTr("Export wallet to Coldcard")
var STR_QML_446 = qsTr("Show as QR code")

//SCR_STARTING_CREATE_SIGNER.qml
var STR_QML_447 = qsTr("You don’t have any key yet.")
var STR_QML_448 = qsTr("Please add a key before assigning it to the collaborative wallet")
var STR_QML_449 = qsTr("Take me to add a key")

//SCR_UPDATE_PROFILE.qml
var STR_QML_450 = qsTr("Update profile")
var STR_QML_451 = qsTr("Name")
var STR_QML_452 = qsTr("Upload photo")
var STR_QML_453 = qsTr("Remove photo")
var STR_QML_454 = qsTr("Save changes")

//Component *.qml
var STR_QML_455 = qsTr("Health check")
var STR_QML_456 = qsTr("Replaced")
var STR_QML_457 = qsTr("Enter your passphrase")
var STR_QML_458 = qsTr("Your PIN Number")
var STR_QML_459 = qsTr("Send PIN")
var STR_QML_460 = qsTr("Update profile")
var STR_QML_461 = qsTr("Settings")
var STR_QML_462 = qsTr("Sign out")
var STR_QML_463 = qsTr("Welcome to Wallet Manager")
var STR_QML_464 = qsTr("Congrats on your first key! Now you can create a new wallet using the key you have added.")
var STR_QML_465 = qsTr("Start managing your Bitcoin wallets all in one place by adding a new key.")
var STR_QML_466 = qsTr("Are you sure you want to cancel this wallet?")
var STR_QML_467 = qsTr("Ignore")
var STR_QML_468 = qsTr("Accept")
var STR_QML_469 = qsTr("Pending")
var STR_QML_470 = qsTr("Withdraw request")
var STR_QML_471 = qsTr("No name")
var STR_QML_472 = qsTr("Members")
var STR_QML_473 = qsTr("Would you like to create a collaborative wallet?")
var STR_QML_474 = qsTr("A collaborative wallet is one of the safest ways to store your bitcoin because it eliminates single points of failure. Want to learn more about collaborative wallets? <a href='%1'>Read our guide.</a>")
var STR_QML_475 = qsTr("No, thanks")
var STR_QML_476 = qsTr("Create a collaborative wallet")
var STR_QML_477 = qsTr("Delivered")
var STR_QML_478 = qsTr("Sending")
var STR_QML_479 = qsTr("Unknown")
var STR_QML_480 = qsTr("Creating a %1/%2 %3 wallets")
var STR_QML_481 = qsTr("escrow")
var STR_QML_482 = qsTr("standard")
var STR_QML_483 = qsTr("Canceled")
var STR_QML_484 = qsTr("View config")
var STR_QML_485 = qsTr("Creating a <b>%1 %2</b>")
var STR_QML_486 = qsTr("Pending %1 keys")
var STR_QML_487 = qsTr("Deny wallet")
var STR_QML_488 = qsTr("View details")
var STR_QML_489 = qsTr("Do it now")
var STR_QML_490 = qsTr("N/A")
var STR_QML_491 = qsTr("Sending to ")
var STR_QML_492 = qsTr("Confirmed")
var STR_QML_493 = qsTr("Enough signatures collected")
var STR_QML_494 = qsTr("signatures")
var STR_QML_495 = qsTr("signature")
var STR_QML_496 = qsTr("Sign transaction")
var STR_QML_497 = qsTr("Broadcast transaction")
var STR_QML_498 = qsTr("The transaction to <b>%1...%2</b> has been confirmed")
var STR_QML_499 = qsTr("You received")
var STR_QML_500 = qsTr("You're receiving")
var STR_QML_501 = qsTr("Chat info")
var STR_QML_502 = qsTr("Please select chat room")
var STR_QML_503 = qsTr("Add members")
var STR_QML_504 = qsTr("Leave group")
var STR_QML_505 = qsTr("Pending transactions")
var STR_QML_506 = qsTr("Please plug in and unlock your device")
var STR_QML_507 = qsTr("Please sign using export and import transaction button.")
var STR_QML_508 = qsTr("This is a software key resided in another device")
var STR_QML_509 = qsTr("Sign")
var STR_QML_510 = qsTr("Rescan")
var STR_QML_511 = qsTr("Assigned")

var STR_QML_512 = qsTr("Edit profile")
var STR_QML_513 = qsTr("Display unit (BTC)")
var STR_QML_514 = qsTr("Network settings")
var STR_QML_515 = qsTr("Hardware driver")
var STR_QML_516 = qsTr("Change your password")
var STR_QML_517 = qsTr("Logged-in devices")
var STR_QML_518 = qsTr("About")
var STR_QML_519 = qsTr("Display unit")
var STR_QML_520 = qsTr("Show Fixed Precision")
var STR_QML_521 = qsTr("Network Settings")
var STR_QML_522 = qsTr("Connect to Electrum server")
var STR_QML_523 = qsTr("Path to Your SSL Certificate")
var STR_QML_524 = qsTr("Upload SSL file")
var STR_QML_525 = qsTr("Change password")
var STR_QML_526 = qsTr("Current password")
var STR_QML_527 = qsTr("Update password")
var STR_QML_528 = qsTr("Save network settings")
var STR_QML_529 = qsTr("Reset to default network settings")
var STR_QML_530 = qsTr("Database Encryption")
var STR_QML_531 = qsTr("Confirm passphrase doesn't match passphrase")
var STR_QML_532 = qsTr("Import PSBT")
var STR_QML_533 = qsTr("Sign in")
var STR_QML_534 = qsTr("Apply")
var STR_QML_535 = qsTr("Guest")
var STR_QML_536 = qsTr("Verifying")
var STR_QML_537 = qsTr("Account Settings")
var STR_QML_538 = qsTr("Add account")
var STR_QML_539 = qsTr("Delete account")
var STR_QML_540 = qsTr("Deleting your account is a permanent action")
var STR_QML_541 = qsTr("Adding your account is a permanent action")

var STR_QML_542 = qsTr("Are you sure you want to delete this account? Please type DELETE to confirm.")
var STR_QML_543 = qsTr("Confirm account deletion")
var STR_QML_544 = qsTr("We've sent a confirmation code to <b>%1.</b> Please enter the code below to confirm the deletion of this account")
var STR_QML_545 = qsTr("Your password has successfully been updated")
var STR_QML_546 = qsTr("Mark as compromised")
var STR_QML_547 = qsTr("Sign out of all devices")
var STR_QML_548 = qsTr("Signd out")
var STR_QML_549 = qsTr("Unknown")
var STR_QML_550 = qsTr("Your contact request has been sent")
var STR_QML_551 = qsTr("Your invitation has been sent")
var STR_QML_552 = qsTr("Text size must be more than or equal 5 characters")
var STR_QML_553 = qsTr("Taproot")

var STR_QML_554 = qsTr("This key is currently being used in a wallet. Please remove the wallet first.")
var STR_QML_555 = qsTr("Please remove this key on the device that it was added to.")

var STR_QML_556 = qsTr("Current wallet config")
var STR_QML_557 = qsTr("Not configured")
var STR_QML_558 = qsTr("Single-sig")
var STR_QML_559 = qsTr("%1/%2 multisig")
var STR_QML_560 = qsTr("Top up XPUBs")
var STR_QML_561 = qsTr("Placeholder default message")
var STR_QML_562 = qsTr("This is placeholder of signature automatically generated after export message")


var STR_QML_570 = qsTr("Spend from collaborative wallet")
var STR_QML_571 = qsTr("Please download and install the update from our website")
var STR_QML_572 = qsTr("I'll do this later")
var STR_QML_573 = qsTr("Update recommended")
var STR_QML_574 = qsTr("View wallet config")
var STR_QML_575 = qsTr("That does not look like a valid email address")

var STR_QML_576 = qsTr("Are you sure you want to sign out %1?")
var STR_QML_577 = qsTr("Are you sure you want to mark %1 as compromised? The device’s access to messages and wallets will be removed.")
var STR_QML_578 = qsTr("Are you sure you want to sign out all devices")

var STR_QML_579 = qsTr("%1 has been marked as compromised")
var STR_QML_580 = qsTr("All devices have been deleted")
var STR_QML_581 = qsTr("%1 has been deleted")

var STR_QML_582 = qsTr("Topping up XPUBs")
var STR_QML_583 = qsTr("Signet Server")
var STR_QML_584 = qsTr("Signet")
var STR_QML_585 = qsTr("Explorer address")

var STR_QML_586 = qsTr("Changes are saved")
var STR_QML_587 = qsTr("Please name your wallet")

var STR_QML_588 = qsTr("Developer settings")
var STR_QML_589 = qsTr("Debug mode")

var STR_QML_590 = qsTr("You might not be able to read encrypted messages from the original device. A Device Verification feature will allow you to do so in the feature. Follow us on Twitter for updates.")
var STR_QML_591 = qsTr("Type contact's email or username")
var STR_QML_592 = qsTr("Get started")
var STR_QML_593 = qsTr("Multi-device sync (experimental)")

var STR_QML_594 = qsTr("Nunchuk")
var STR_QML_595 = qsTr("Invalid delete account confirmation code")
var STR_QML_596 = qsTr("Ok")

var STR_QML_597 = qsTr("Guest mode")
var STR_QML_598 = qsTr("Guest mode allows you to create keys and wallets without an account. Please consider the following before using—")
var STR_QML_599 = qsTr("Keys and wallets created in guest mode are stored locally. They will not be removed until you manually delete them or uninstall the app.")
var STR_QML_600 = qsTr("Messaging and collaborative multisig wallets (*) are currently not available in guest mode.")
var STR_QML_601 = qsTr("*A collaborative multisig wallet is a wallet where you co-manage bitcoin with other people.")

var STR_QML_602 = qsTr("Send a message")

//SCR_RECOVER_SHARED_WALLET.qml
var STR_QML_603 = qsTr("Recover collaborative wallet")
var STR_QML_604 = qsTr("In order to recover a collaborative wallet, you will need:")
var STR_QML_605 = qsTr("Room members to recover the keys from the original wallet")
var STR_QML_606 = qsTr("A copy of the wallet configuration file (BSMS or descriptors)")
var STR_QML_607 = qsTr("Recover using BSMS/descriptors")
var STR_QML_608 = qsTr("Recover using QR code")

var STR_QML_609 = qsTr("Are you sure you want to delete this contact? This cannot be undone.")
var STR_QML_610 = qsTr("You currently have a collaborative wallet with this contact. Please remove the wallet before removing the contact.")

var STR_QML_611 = qsTr("Online")
var STR_QML_612 = qsTr("Offline")
var STR_QML_613 = qsTr("Syncing")

var STR_QML_614 = qsTr("Please add a key before adding a wallet")
var STR_QML_615 = qsTr("Hardware, software and air-gapped keys are supported.")

var STR_QML_616 = qsTr("Looks like you have added a signer")
var STR_QML_617 = qsTr("Do you want to add a Bitcoin wallet?")

var STR_QML_618 = qsTr("Message function require an account")
var STR_QML_619 = qsTr("We use email as the user ID for shared wallet and interpersonal messaging features.")
var STR_QML_620 = qsTr("First and last name")

var STR_QML_621 = qsTr("Enter the confirmation code we sent to %1. <a href='dummycode.tbd'>Resend code</a>")

var STR_QML_622 = qsTr("Set your password")
var STR_QML_623 = qsTr("Your password must consist of 6 characters, at least 1 numer or symbol and atleast 1 letter.")
var STR_QML_624 = qsTr("Confirm password")

var STR_QML_625 = qsTr("You have no messages.")
var STR_QML_626 = qsTr("Send to")
var STR_QML_627 = qsTr("Do more with Nunchuk")
var STR_QML_628 = qsTr("Create an account or sign in to take advantage of our messenger and collaborative multisig wallet")

var STR_QML_629 = qsTr("Primary Key account")
var STR_QML_630 = qsTr("A Primary Key is a dual-purpose key that can be used both for account-based authentication and for signing Bitcoin transactions.")
var STR_QML_631 = qsTr("A Primary Key account is an account that does not require any personal information, including email addresses.")

var STR_QML_632 = qsTr("Sign in remotely via QR")
var STR_QML_633 = qsTr("Sign in manually")
var STR_QML_634 = qsTr("Import Primary Keys")

var STR_QML_635 = qsTr("Create an account using Primary Key")
var STR_QML_636 = qsTr("Add a Primary Key")
var STR_QML_637 = qsTr("Wired keys are supported. Support for air-gapped Primary Key coming soon.")

var STR_QML_638 = qsTr("Choose your username")
var STR_QML_639 = qsTr("The default username is the fingerprint (XFP) of your Primary Key. You can change this to something else.")
var STR_QML_640 = qsTr("Username")

var STR_QML_641 = qsTr("Primary Key")
var STR_QML_642 = qsTr("Are you sure you don’t want a passphrase? A Primary Key without a passphrase means that your account is unprotected. Anyone who has access to your device can access all your data, including your wallets.")
var STR_QML_643 = qsTr("Sign in using Primary Key")

var STR_QML_644 = qsTr("Please enter the seed phrase.")
var STR_QML_645 = qsTr("Passphrase")
var STR_QML_646 = qsTr("Please enter the passphrase associated with the Primary Key. If you don’t have one, leave it blank.")

var STR_QML_647 = qsTr("Your username")
var STR_QML_648 = qsTr("Challenge message")
var STR_QML_649 = qsTr("Your signature")
var STR_QML_650 = qsTr("Add Primary Key account")

var STR_QML_651 = qsTr("Copied to clipboard")
var STR_QML_652 = qsTr("Refresh")
var STR_QML_653 = qsTr("Primary Key accounts")
var STR_QML_654 = qsTr("For wired Primary Key account, please ensured the wired key is plugged in and unlocked")

var STR_QML_655 = qsTr("Add or sign in remotely")
var STR_QML_656 = qsTr("Primary Key name")

var STR_QML_657 = qsTr("Replace Primary Key")
var STR_QML_658 = qsTr("A Primary Key is a dual-purpose key that can be used both for account-based authentication and for signing Bitcoin transactions. Please note the following:")
var STR_QML_659 = qsTr("If you choose to proceed, your Primary Key will be replaced with a new one. Your current Primary Key will be downgraded to a regular key.")
var STR_QML_660 = qsTr("If you have assigned the current Primary Key to any wallets, those wallets will remain unchanged. You will need the existing key in order to sign transactions in those wallets. Please do not delete it if there is still a balance.")
var STR_QML_626_ = qsTr("Receive address")
var STR_QML_661 = qsTr("Warning")
var STR_QML_662 = qsTr("Deleting this collaborative wallet will also delete the corresponding chat. Are you sure you want to delete?")

var STR_QML_663 = qsTr("Could not change the passhrase for database")
var STR_QML_664 = qsTr("Change the passhrase for database successfully!")
var STR_QML_665 = qsTr("Passphrase adds another layer of security to your key. You will need to enter the passphrase every time you use this key. You can think of it as the 25th word of your seed phrase.")
var STR_QML_666 = qsTr("We strongly recommend adding a passphrase for your Primary Key.")

var STR_QML_667 = qsTr("Wrong passphrase")
var STR_QML_668 = qsTr("Copied to clipboard")
var STR_QML_669 = qsTr("Neither this account nor this key has a passphrase. Anyone who has access to your device can use this key to sign malicious transactions.")
var STR_QML_670 = qsTr("I understand the risk")
var STR_QML_671 = qsTr("Could not create account");

var STR_QML_672 = qsTr("Are you sure you want to delete this account? All your keys and wallets will be removed. Please make sure that you have backups.")
var STR_QML_673 = qsTr("Please type DELETE to confirm.")

var STR_QML_674 = qsTr("Export wallet to BitBox")
var STR_QML_675 = qsTr("Encrypted")
var STR_QML_676 = qsTr("Select the key you want to add")
var STR_QML_677 = qsTr("Import via file")
var STR_QML_678 = qsTr("NFC")
var STR_QML_679 = qsTr("Assisted")
var STR_QML_680 = qsTr("Iron Hand")
var STR_QML_681 = qsTr("Honey Badger")
var STR_QML_682 = qsTr("Manage subscription")
var STR_QML_683 = qsTr("Take me to the website")
var STR_QML_684 = qsTr("Please manage your subscription through our website. Sign in and navigate to the Plan and Invoices page.")
var STR_QML_685 = qsTr("NFC")
var STR_QML_686 = qsTr("Force refresh (advanced)")
var STR_QML_687 = qsTr("Are you sure you want to sign this transaction")
var STR_QML_688 = qsTr("Please use the mobile app to sign with this key.")
var STR_QML_689_free = qsTr("Are you sure you want to perform a force refresh? This process will clear this wallet’s existing data (including notes and pending transactions) and attempt to re-sync it with the blockchain.")
var STR_QML_689 = qsTr("Are you sure you want to perform a force refresh?")
var STR_QML_690 = qsTr("The wallet has been refreshed")
var STR_QML_691 = qsTr("Copy transaction ID")
var STR_QML_692 = qsTr("You don't have any transaction yet")
var STR_QML_693 = qsTr("Couldn't determine how to open the file, opening its folder instead")
var STR_QML_694 = qsTr("Couldn't determine how to open the file or its folder.")
var STR_QML_695 = qsTr("Attachment file is invalid")
var STR_QML_696 = qsTr("Allow only one file")

var STR_QML_697 = qsTr("Emergency lockdown")
var STR_QML_698 = qsTr("Key recovery")
var STR_QML_699 = qsTr("Your subscription")
var STR_QML_700 = qsTr("Order new hardware")
var STR_QML_701 = qsTr("Support")
var STR_QML_702 = qsTr("Emergency")

var STR_QML_703 = qsTr("If you feel that there is an imminent threat or just want to disable wallet access \n \
temporarily, you can activate the emergency lockdown. Please note the following:")
var STR_QML_704 = qsTr("Once you have entered the lockdown, no one—including yourself—will be able to \n \
sign in to your account and access your wallet.")
var STR_QML_705 = qsTr("There is no way to end the lockdown early.")
var STR_QML_706 = qsTr("Access will be automatically re-enabled once the lockdown period ends.")
var STR_QML_707 = qsTr("Get additional wallets")
var STR_QML_708 = qsTr("Start key recovery")
var STR_QML_709 = qsTr("Re-enter your password")
var STR_QML_710 = qsTr("For security, please re-enter your password.")

var STR_QML_711 = qsTr("Select your lockdown period")
var STR_QML_712 = qsTr("Your access will be automatically re-enabled once the lockdown period ends.")

var STR_QML_716 = qsTr("Answer security question")
var STR_QML_717 = qsTr("What is your nickname when you were young?")
var STR_QML_718 = qsTr("Answer")
var STR_QML_719 = qsTr("Please answer the following question. Answer is case-sensitive.")
var STR_QML_720 = qsTr("Your account is now under lockdown")
var STR_QML_721 = qsTr("The lockdown will last <b>%1</b>.")

var STR_QML_722 = qsTr("If you lost a TAPSIGNER or the card malfunctions, this procedure will recover the \n \
TAPSIGNER’s private key using the encrypted backup from the server. Please note the \n \
following:")
var STR_QML_723 = qsTr("Once you have entered the lockdown, no one—including yourself—will \n \
be able to sign in to your account and access your wallet.")
var STR_QML_724 = qsTr("There is no way to end the lockdown early.")

var STR_QML_725 = qsTr("Enter Backup Password")
var STR_QML_726 = qsTr("Please enter the Backup Password for [<b>%1</b>] (card ID: <b>••%2</b>).")
var STR_QML_727 = qsTr("Backup Password")
var STR_QML_727_optinal = qsTr("Backup Password #2 (optional)")
var STR_QML_728 = qsTr("The key recovery procedure currently only supports TAPSIGNER.")
var STR_QML_729 = qsTr("Please select the TAPSIGNER you want to recover")
var STR_QML_730 = qsTr("TAPSIGNER recovered")
var STR_QML_731 = qsTr("Your TAPSIGNER’s private key has been successfully recovered and \n \
converted into a software key. Please note the following:")
var STR_QML_732 = qsTr("The software key is stored on this device")
var STR_QML_733 = qsTr("You can continue signing transactions using this software key")
var STR_QML_734 = qsTr("If you suspect that someone has gained possession of the key, we recommend that you roll \n \
over your balance to a new wallet.")
var STR_QML_735 = qsTr("You can order new hardware by using the referral links on our website. Sign in and navigate to the Hardware Replacement page.")
var STR_QML_736 = qsTr("Inheritance planning")
var STR_QML_737 = qsTr("Claim an inheritance")
var STR_QML_738 = qsTr("Platform key co-signing policies")
var STR_QML_739 = qsTr("TAPSIGNER has been recovered.")
var STR_QML_740 = qsTr("The password is printed on the back of the TAPSIGNER. You should have had a copy of this \n \
when setting up the TAPSIGNER for the first time.")
var STR_QML_741 = qsTr("Local currency (%1)")
var STR_QML_742 = qsTr("Local currency")
var STR_QML_743 = qsTr("Need support? Chat with an expert")
var STR_QML_744 = qsTr("You currently do not have any TAPSIGNER added.")
var STR_QML_745 = qsTr("Photos and videos")
var STR_QML_746 = qsTr("Upload file")

var STR_QML_747 = qsTr("Claim inheritance")
var STR_QML_748 = qsTr("Please enter the Magic Phrase and Backup Password")
var STR_QML_749 = qsTr("Magic Phrase")
var STR_QML_750 = qsTr("It looks like the original subscription has expired for more than 3 years. To claim the inheritance, please reactivate the plan first by visiting nunchuk.io/claim.")
var STR_QML_751 = qsTr("Take me to reactivate the plan")
var STR_QML_752 = qsTr("Your inheritance plan has not been activated yet. Please try again later.")
var STR_QML_753 = qsTr("Become a subscriber to get access to our services.")

var STR_QML_754 = qsTr("Get more out of Nunchuk with an assisted wallet")
var STR_QML_755 = qsTr("Here are some of the things that you can do with an assisted wallet:")
var STR_QML_756 = qsTr("No single point of failure")
var STR_QML_757 = qsTr("Eliminate single points of failure by using multisig: two keys are always required for spending. The loss of any one key will not compromise your funds.")
var STR_QML_759 = qsTr("Plan your inheritance in a non-custodial way and ensure that your bitcoins can be safely passed on to your loved ones. Compatible with existing estate plans.")
var STR_QML_762 = qsTr("Lock your wallet access when there is a security threat or when you go off the grid.")
var STR_QML_763 = qsTr("Flexible spending policies")
var STR_QML_764 = qsTr("Set up scheduled payments, extra security measures when withdrawing large amounts of bitcoins, and more.")
var STR_QML_765 = qsTr("Cloud backups and assisted recovery")
var STR_QML_766 = qsTr("Have peace of mind knowing that your wallet backups are encrypted and stored securely in the cloud. Assisted recovery is a breeze.")
var STR_QML_767 = qsTr("In-app chat support")
var STR_QML_768 = qsTr("Chat to an expert directly within the app when you run into issues.")
var STR_QML_770 = qsTr("Tell me more")

var STR_QML_771 = qsTr("Please start the claiming process by visiting nunchuk.io/claim.")
var STR_QML_772 = qsTr("Take me there")

var STR_QML_773 = qsTr("Buffer period has started")
var STR_QML_774 = qsTr("The owner of this plan set up a buffer period before the inheritance can be claimed.")
var STR_QML_774_ = qsTr("Please check back in <b>%1</b>.")
var STR_QML_775 = qsTr("Your inheritance")
var STR_QML_776 = qsTr("Congratulations! You have unlocked your inheritance")
var STR_QML_777 = qsTr("Done")
var STR_QML_778 = qsTr("Withdraw balance")
var STR_QML_779 = qsTr("Withdraw to a Nunchuk wallet")
var STR_QML_780 = qsTr("Withdraw to an address")
var STR_QML_781 = qsTr("You have a message below")

var STR_QML_782 = qsTr("Which wallet do you want to withdraw bitcoin to?")
var STR_QML_783 = qsTr("View on blockchain explorer")
var STR_QML_784 = qsTr("Confirm and withdraw balance")
var STR_QML_785 = qsTr("Transaction details")
var STR_QML_786 = qsTr("New transaction")
var STR_QML_787 = qsTr("Enter recipient’s address")

var STR_QML_788 = qsTr("Congratulations!")
var STR_QML_789 = qsTr("Your inheritance has been claimed.")
var STR_QML_790 = qsTr("Hardware key discounts")
var STR_QML_791 = qsTr("Get exclusive discounts when purchasing hardware signing devices from our partners.")
var STR_QML_792 = qsTr("Broadcast and delay")
var STR_QML_793 = qsTr("You can always bypass the co-signing delay by using your own keys.")
var STR_QML_794 = qsTr("Automatically broadcast transaction after co-signing")
var STR_QML_795 = qsTr("Enable co-signing delay")
var STR_QML_796 = qsTr("A co-signing delay gives you time to detect errors or unauthorized acccess before a transaction is broadcast.")
var STR_QML_797 = qsTr("Hours")
var STR_QML_798 = qsTr("Minutes")

var STR_QML_799 = qsTr("Spending limit")
var STR_QML_800 = qsTr("The platform key will only co-sign transactions if the total amount spent has not exceeded the spending limit.")
var STR_QML_801 = qsTr("Co-signing spending limit")
var STR_QML_802 = qsTr("Broadcast and delay")
var STR_QML_803 = qsTr("%1: Platform key co-signing policies")
var STR_QML_804 = qsTr("Continue to save changes")
var STR_QML_805 = qsTr("Discard changes")
var STR_QML_806 = qsTr("Increasing the co-signing spending limit requires signing a dummy transaction. Please do so via the mobile app.")
var STR_QML_807 = qsTr("The estimated fee is calculated using current market conditions. You can set your own fee by toggling the customize fee setting.")
var STR_QML_808 = qsTr("Please set a delay that is less than 168 hours.")
var STR_QML_809 = qsTr("Transactions with fee too low might get kicked out of the mempool. Are you sure you want to continue?")

var STR_QML_810 = qsTr("Add Ledger to your assisted wallet")
var STR_QML_811 = qsTr("Add Ledger")
var STR_QML_812 = qsTr("It looks like you want to add Ledger as a hardware key to an assisted wallet. Would you like to do it now?")

var STR_QML_813 = qsTr("Add Trezor to your assisted wallet")
var STR_QML_814 = qsTr("Add Trezor")
var STR_QML_815 = qsTr("It looks like you want to add Trezor as a hardware key to an assisted wallet. Would you like to do it now?")

var STR_QML_816 = qsTr("Insufficient funds")
var STR_QML_817 = qsTr("Please ensure to do the following before proceeding.")
var STR_QML_818 = qsTr("Initialize the device key")
var STR_QML_819 = qsTr("Follow Ledger’s instruction on how to set up your device with a seed phrase.")
var STR_QML_820 = qsTr("To unlock the device, you might need to enter a PIN and/or a PASSPHRASE directly on the device screen.")

var STR_QML_821 = qsTr("Install the Bitcoin app")
var STR_QML_822 = qsTr("If you haven’t already, install the Bitcoin (BTC) app on the Ledger device. Please refer to Ledger’s guide.")

var STR_QML_824 = qsTr("Please ensure that the Ledger device is connected to this computer, and click on Refresh.")
var STR_QML_825 = qsTr("Configure gap limit (advanced)")
var STR_QML_826 = qsTr("Adding Ledger... Please keep your device connected.")

var STR_QML_827 = qsTr("Ledger added successfully")
var STR_QML_828 = qsTr("To finish setting up your assisted wallet, please return to your mobile device.")

var STR_QML_829 = qsTr("Follow Trezor’s instruction on how to set up your device with a seed phrase.")
var STR_QML_830 = qsTr("Please ensure that the Trezor device is connected to this computer, and click on Refresh.")
var STR_QML_831 = qsTr("Adding Trezor... Please keep your device connected.")
var STR_QML_832 = qsTr("Trezor added successfully")
var STR_QML_833 = qsTr("Gap limit has been updated")
var STR_QML_834 = qsTr("Gap limit cannot exceed 100.")

var STR_QML_835 = qsTr("Save")
var STR_QML_836 = qsTr("Effective package fee rate: %1 sat/vB")
var STR_QML_837 = qsTr("Select an assisted wallet")
var STR_QML_838 = qsTr("Which wallet do you want to select?")

var STR_QML_839 = qsTr("This feature is only available with an assisted wallet. Please create one first.")
var STR_QML_840 = qsTr("No Trezor devices have been detected. Please try again.")

var STR_QML_841 = qsTr("You have <b>%1</b> remaining assisted wallets. You can get additional wallets through our website. Sign in and navigate to the Plan and Invoices page.")
var STR_QML_842 = qsTr("You have <b>%1</b> remaining assisted wallet. You can get additional wallet through our website. Sign in and navigate to the Plan and Invoices page.")
//=================
var STR_QML_843 = qsTr("Review your plan")
var STR_QML_844 = qsTr("Cancel inheritance plan")
var STR_QML_845 = qsTr("Wallet subject to inheritance:")
var STR_QML_846 = qsTr("View claiming instructions")
var STR_QML_847 = qsTr("Share your secrets")
var STR_QML_848 = qsTr("Activation Date")
var STR_QML_849 = qsTr("Edit")
var STR_QML_850 = qsTr("Note to Beneficiary or Trustee")
var STR_QML_851 = qsTr("Buffer period")
var STR_QML_852 = qsTr("Nofication preferences")
var STR_QML_853 = qsTr("Continue to finalize changes")
//===================
var STR_QML_854 = qsTr("Set up an Activation Date")
var STR_QML_855 = qsTr("<b>Only on or after this date</b>, a Beneficiary or Trustee can claim the inheritance. \n
You can change the Activation Date later via the Services tab.")
var STR_QML_856 = qsTr("Even with the correct Magic Phrase and Backup Password, one cannot claim the inheritance before this date.")
var STR_QML_857 = qsTr("Update activation date")
var STR_QML_858 = qsTr("Would you like to leave a message?")
var STR_QML_859 = qsTr("After the Beneficiary or Trustee claims the inheritance, they will be able to \n \
see this message.")
var STR_QML_860 = qsTr("Note")
var STR_QML_861 = qsTr("Update message")
var STR_QML_862 = qsTr("Set up buffer period")
var STR_QML_863 = qsTr("A buffer period is extra time that you can add after the claimant has provided \n \
the secrets and before the inheritance can be claimed. The buffer period \n \
helps you prevent unauthorized claims. \n \
\n \
An email notification will be sent when the buffer period begins.")

var STR_QML_864 = qsTr("Update buffer period")
var STR_QML_865 = qsTr("Notification preferences")
var STR_QML_866 = qsTr("On the Activation Date, would you like us to notify the Beneficiary or Trustee of the inheritance plan? If so, please provide an email address.")
var STR_QML_867 = qsTr("Beneficiary’s or Trustee’s email address")
var STR_QML_868 = qsTr("Also notify them today")
var STR_QML_869 = qsTr("You are still personally responsible for sharing the Magic Phrase and Backup Password with the Beneficiary or Trustee. The notification email won’t include these information.")
var STR_QML_870 = qsTr("Update notification preferences")
var STR_QML_871 = qsTr("I don’t want any notifications")

var STR_QML_872 = qsTr("Are you sure want to discard the changes?")
var STR_QML_873 = qsTr("Moving the Activation Date earlier requires signing a dummy transaction. Please do so via the mobile app.")
var STR_QML_875 = qsTr("View inheritance plan")

var STR_QML_876 = qsTr("30-day buffer")
var STR_QML_877 = qsTr("7-day buffer")
var STR_QML_878 = qsTr("I don’t need a buffer period")
var STR_QML_879 = qsTr("Recommended")

var STR_QML_880 = qsTr("The Magic Phrase and Backup Password must be shared with the party or \n \
parties eligible for the inheritance. Please select your option:")

var STR_QML_881 = qsTr("Direct inheritance")
var STR_QML_882 = qsTr("The Beneficiary has full control over the inheritance. Upon the \n \
Activation Date, they can claim the inheritance for themselves.")

var STR_QML_883 = qsTr("Indirect inheritance")
var STR_QML_884 = qsTr("A Trustee has full control over the inheritance. Upon the Activation \n \
Date, the Trustee can help the Beneficiary claim the inheritance on their behalf.")

var STR_QML_885 = qsTr("Joint control")
var STR_QML_886 = qsTr("The Beneficiary and the Trustee have joint control over the \n \
inheritance. Upon the Activation Date, the Beneficiary and Trustee \n \
will need to combine their secrets in order to claim the \n \
inheritance.")

var STR_QML_887 = qsTr("Please share these two secrets with the \n \
Beneficiary:")
var STR_QML_888 = qsTr("The plan’s Magic Phrase.")
var STR_QML_889 = qsTr("The Backup Password for the encrypted \n \
backup, which can be found on the back of \n \
the TAPSIGNER designated for inheritance. \n \
(It might be listed under “Backup key”).")
var STR_QML_890 = qsTr("You are solely responsible for sharing \n \
the Magic Phrase and Backup \n \
Password with the Beneficiary. Failure to \n \
share will result in the inheritance \n \
being unclaimable.")
var STR_QML_891 = qsTr("Please share these two secrets with the Trustee:")
var STR_QML_892 = qsTr("<b></b>Please share one secret with the Beneficiary and \n \
the other secret with the Trustee. <b>Neither party \n \
should have both secrets.</b>")
var STR_QML_893 = qsTr("You are solely responsible for sharing the Magic Phrase and Backup \n \
Password with the Trustee. Failure to \n \
share will result in the inheritance \n \
being unclaimable.")
var STR_QML_894 = qsTr("You are solely responsible for sharing \n \
the Magic Phrase and Backup \n \
Password with the Beneficiary and the \n \
Trustee. Failure to share will result in \n \
the inheritance being unclaimable.")

var STR_QML_895 = qsTr("This transaction includes unconfirmed coins.")
var STR_QML_897 = qsTr("Canceling the inheritance requires signing a dummy transaction. Please do so via the mobile app.")
var STR_QML_898 = qsTr("Wired")
var STR_QML_899 = qsTr("Add existing key")
var STR_QML_900 = qsTr("Take me to add a new key")
var STR_QML_901 = qsTr("Do you want to add an existing key?")
var STR_QML_902 = qsTr("We noticed that you already have a Ledger in your key manager")

var STR_QML_903 = qsTr("Add COLDCARD to your assisted wallet")
var STR_QML_904 = qsTr("Add COLDCARD")
var STR_QML_905 = qsTr("It looks like you want to add COLDCARD as a hardware key to an assisted wallet. Would you like to do it now?")
var STR_QML_906 = qsTr("No COLDCARD devices have been detected. Please try again.")

var STR_QML_907 = qsTr("Initialize COLDCARD")
var STR_QML_908 = qsTr("Refer to <a href='https://coldcard.com/docs/quick'>this starter guide</a>.")
var STR_QML_909 = qsTr("Unlock COLDCARD")
var STR_QML_910 = qsTr("You might need to enter a PIN and/or a PASSPHRASE directly on COLDCARD.")
var STR_QML_911 = qsTr("Please ensure that the COLDCARD device is connected to this computer, and click on Refresh.")
var STR_QML_912 = qsTr("Adding COLDCARD... Please keep your device connected.")
var STR_QML_913 = qsTr("COLDCARD added successfully")
var STR_QML_914 = qsTr("No COLDCARD devices have been detected. Please try again.")
var STR_QML_915 = qsTr("We noticed that you already have a Trezor in your key manager")
var STR_QML_916 = qsTr("We noticed that you already have a COLDCARD in your key manager")
var STR_QML_917 = qsTr("(The Backup Password is printed on the back of the \n
inheritance key)")
var STR_QML_918 = qsTr("There no assisted wallet")
var STR_QML_919 = qsTr("Are you sure want to discard the changes?")
var STR_QML_920 = qsTr("Would you like to leave a message?")
var STR_QML_921 = qsTr("No buffer")

var STR_QML_922 = qsTr("Add BitBox to your assisted wallet")
var STR_QML_923 = qsTr("Add BitBox")
var STR_QML_924 = qsTr("It looks like you want to add BitBox as a hardware key to an assisted wallet. Would you like to do it now?")
var STR_QML_925 = qsTr("We noticed that you already have a BitBox in your key manager")
var STR_QML_926 = qsTr("Follow BitBox’s instruction on how to set up your device with a seed phrase.")
var STR_QML_927 = qsTr("To unlock the device, you might need to use the BitBox’s companion app. Please close the BitBox’s companion app after you have unlocked the device.")
var STR_QML_928 = qsTr("No BitBox devices have been detected. Please try again.")
var STR_QML_929 = qsTr("Please ensure that the BitBox device is connected to this computer, and click on Refresh")
var STR_QML_930 = qsTr("Adding BitBox... Please keep your device connected")
var STR_QML_931 = qsTr("BitBox added successfully")
var STR_QML_932 = qsTr("Key already assigned to wallet")
var STR_QML_933 = qsTr("No Ledger devices have been detected. Please try again.")
var STR_QML_934 = qsTr("Alerts")
var STR_QML_935 = qsTr("View")
var STR_QML_936 = qsTr("Group wallet creation pending")
var STR_QML_937 = qsTr("%1 initiated a group wallet. If you’re part of this wallet, please add your key.")
var STR_QML_938 = qsTr("Let’s add your keys")
var STR_QML_939 = qsTr("Your new wallet will be a %1-of-%2 multisig wallet. <b>%3</b>")
var STR_QML_939_two = qsTr("Two keys are always required for spending.")
var STR_QML_939_three = qsTr("Three keys are always required for spending.")
var STR_QML_940 = qsTr("Your group will have possession of three keys. The fourth key will be held by Nunchuk on our secure server.")

var STR_QML_940_one = qsTr("Among your keys, select one key to be the inheritance key. It must be a TAPSIGNER. \n \
\n \
Pull to refresh the key statuses.")

var STR_QML_940_two = qsTr("Among your keys, select two keys to be the inheritance keys. They must be TAPSIGNERs. \n \
\n \
Pull to refresh the key statuses.")

var STR_QML_940_without = qsTr("Pull to refresh the key statuses.")

var STR_QML_941 = qsTr("Add")
var STR_QML_942 = qsTr("What type of key do you want to add?")
var STR_QML_943 = qsTr("To add other types of keys, please use the mobile app.")
var STR_QML_944 = qsTr("Pending wallet")
var STR_QML_945 = qsTr("<b>%1</b> (%2) invited you to join a group wallet.")
var STR_QML_946 = qsTr("Deny")
var STR_QML_947 = qsTr("Dashboard")
var STR_QML_948 = qsTr("Key health status")

var STR_QML_949 = qsTr("Master")
var STR_QML_950 = qsTr("Keyholder (admin)")
var STR_QML_951 = qsTr("Keyholder")
var STR_QML_952 = qsTr("Keyholder (limited)")
var STR_QML_953 = qsTr("Observer")

var STR_QML_954 = qsTr("Key #%1")
var STR_QML_955 = qsTr("Dismiss")
var STR_QML_956 = qsTr("TAPSIGNER (inh.)")
var STR_QML_957 = qsTr("Platform key")
var STR_QML_958 = qsTr("Configure")
var STR_QML_959 = qsTr("Configured")

var STR_QML_960 = qsTr("Adding %1... Please keep your device connected.")

var STR_QML_961 = qsTr("Please add the inheritance key via the mobile app.")
var STR_QML_962 = qsTr("Please configure the platform key via the mobile app.")

var STR_QML_963 = qsTr("Are you sure you want to deny this wallet invitation?")
var STR_QML_964 = qsTr("Unable to add Ledger")
var STR_QML_965 = qsTr("Unable to add BitBox")
var STR_QML_966 = qsTr("Unable to add COLDCARD")
var STR_QML_967 = qsTr("Unable to add Trezor")
var STR_QML_968 = qsTr("Lost connection to device")
var STR_QML_969 = qsTr("View recurring payments")
var STR_QML_970 = qsTr("Manage group chat history")
var STR_QML_971 = qsTr("Reminders")
var STR_QML_972 = qsTr("Saving Account")
var STR_QML_973 = qsTr("View history")
var STR_QML_974 = qsTr("Request health check")

var STR_QML_975 = qsTr("Last checked: Less than 6 months ago")
var STR_QML_976 = qsTr("Last checked: More than 6 months ago")
var STR_QML_977 = qsTr("Last checked: More than 1 year ago")

var STR_QML_978 = qsTr("Health check procedure")
var STR_QML_979 = qsTr("To complete a health check, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet. Please use the key that you want to health check to sign.")
var STR_QML_980 = qsTr("The dummy transaction uses a fake input and does not move any of your real bitcoins. It will not be broadcast and will be immediately removed afterwards.")

var STR_QML_981 = qsTr("Sign dummy transaction")
var STR_QML_982 = qsTr("Health check procedure")
var STR_QML_983 = qsTr("This signer is connected")
var STR_QML_984 = qsTr("Continue to health check your key.")
var STR_QML_985 = qsTr("Cancel health check")
var STR_QML_986 = qsTr("Health check request has been canceled")
var STR_QML_987 = qsTr("Health check request sent")
var STR_QML_988 = qsTr("The keyholders have been notified of the health check request. Once the request is completed, the health status will be updated in the group dashboard.")

var STR_QML_989 = qsTr("Please register this wallet with your air-gapped device")
var STR_QML_990 = qsTr("You must register this wallet with your air-gapped device before you can use it to sign transactions. \n \
\n \
Please do so by scanning the QR code on the next screen using your device.")
var STR_QML_991 = qsTr("You must register this wallet with your COLDCARD before you can use it to sign transactions.")
var STR_QML_992 = qsTr("You must register this wallet with your BitBox before you can use it to sign transactions.")
var STR_QML_993 = qsTr("Show wallet QR code")
var STR_QML_994 = qsTr("Export Wallet")
var STR_QML_995 = qsTr("Please register this wallet with your COLDCARD")
var STR_QML_996 = qsTr("Please register this wallet with your BitBox")
var STR_QML_997 = qsTr("Done scanning")
var STR_QML_998 = qsTr("Please use the mobile app to health check this key.")
var STR_QML_999 = qsTr("No devices available")
var STR_QML_1000 = qsTr("This is an NFC key, please claim this key using the mobile app.")
var STR_QML_1001 = qsTr("Get the mobile app")
var STR_QML_1002 = qsTr("Co-signing in progress...")
var STR_QML_1003_Pro = qsTr("Byzantine Pro")
var STR_QML_1003_Premier = qsTr("Byzantine Premier")
var STR_QML_1003 = qsTr("Byzantine")
var STR_QML_1004 = qsTr("Try signing again")
var STR_QML_1005 = qsTr("Register wallet")
var STR_QML_1006 = qsTr("Looks like the health check has failed. Note that you might need to register the wallet with the device before it can be used to sign transactions. \n \
\n \
What would you like to do?")
var STR_QML_1007 = qsTr("Accessing the wallet configuration")
var STR_QML_1008 = qsTr("To access the wallet configuration file or export it to your device later, navigate to the wallet → View wallet config → Export.")
var STR_QML_1009 = qsTr("Spending limit")
var STR_QML_1010 = qsTr("<b>%1</b> (%2) is requesting to make the following changes to the platform key co-signing policies.")
var STR_QML_1011 = qsTr("Continue (%1 signature%2 pending)")
var STR_QML_1014 = qsTr("Signatures required")

var STR_QML_1015 = qsTr("Transaction updated")
var STR_QML_1016 = qsTr("Policies have been updated.")

var STR_QML_1017 = qsTr("Claim your key")
var STR_QML_1018 = qsTr("Please claim your key by performing a key health check. Select your key and continue.")
var STR_QML_1019 = qsTr("Roll over to a new assisted wallet")

var STR_QML_1020 = qsTr("Group wallets")
var STR_QML_1021 = qsTr("Collaboratively create group wallets with others. Manage keys distributedly, control member access or chat privately.")
var STR_QML_1022 = qsTr("Services are currently not available for observers.")

var STR_QML_1023 = qsTr("Key security tip")
var STR_QML_1024 = qsTr("For maximum security, keep your keys geographically distributed.")
var STR_QML_1025 = qsTr("All of your assisted wallets are already under lockdown.")

var STR_QML_1026 = qsTr("Confirm lockdown")
var STR_QML_1027 = qsTr("Code")
var STR_QML_1028_bottom = qsTr("We’ve sent a code to <b>%1</b>. Please enter it above.")
var STR_QML_1028_top = qsTr("We’ve sent a code to <b>%1</b>. Please enter it below.")

var STR_QML_1029 = qsTr("%1 is now under lockdown")

var STR_QML_1030 = qsTr("The platform key will only co-sign transactions if the total amount spent has not \n \
exceeded the spending limit. You can bypass the spending limit by signing transactions \n \
using two of your own keys.")

var STR_QML_1031 = qsTr("Member %1")
var STR_QML_1032 = qsTr("Apply the same limit to all members")
var STR_QML_1033 = qsTr("Lockdown in progress")

var STR_QML_1034 = qsTr("<b>%1</b> (%2) is requesting to cancel the inheritance plan for <b>%3:</b>")
var STR_QML_1035 = qsTr("<b>%1</b> (%2) is requesting to create the inheritance plan for <b>%3:</b>")
var STR_QML_1036 = qsTr("<b>%1</b> (%2) is requesting to make the following changes to the inheritance plan for <b>%3:</b>")

var STR_QML_1012 = qsTr("To authorize the changes, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet. Since more than one signature is required, other keyholders in the group will also be notified.")
var STR_QML_1013 = qsTr("The dummy transaction uses a fake input and does not move any of your real bitcoins. It will not be broadcast and will be immediately removed afterwards.")
var STR_QML_1037 = qsTr("To authorize the changes, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet.")
var STR_QML_1038 = qsTr("To authorize the inheritance planning request, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet. Since more than one signature is required, other keyholders in the group will also be notified.")

var STR_QML_1039 = qsTr("Two signatures are required to cancel the inheritance plan. \n \
\n \
In order to cancel the plan, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet.")

var STR_QML_1040 = qsTr("The dummy transaction will not be broadcast and will be immediately removed afterwards.")

var STR_QML_1041 = qsTr("To authorize this recurring payment, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet. Since more than one signature is required, other keyholders in the group will also be notified.")

var STR_QML_1042 = qsTr("<b>%1</b> (%2) is requesting to set up the inheritance plan for <b>%3</b>.")

var STR_QML_1043 = qsTr("Note that the person in charge of the plan will be able to access sensitive data that unlocks the inheritance.")
var STR_QML_1044 = qsTr("Approve (%1 signature%2 pending)")
var STR_QML_1044_Approve = qsTr("Approve")

var STR_QML_1045 = qsTr("Are you sure you want to deny this inheritance planning request?")
var STR_QML_1046 = qsTr("Customize key account")
var STR_QML_1047 = qsTr("Note to beneficiary")

var STR_QML_1048 = qsTr("Please set up the inheritance plan on mobile.")
var STR_QML_1049 = qsTr("Cancel pending wallet")

var STR_QML_1050 = qsTr("Add COLDCARD via a file")
var STR_QML_1051 = qsTr("Confirm recovery")

var STR_QML_1052 = qsTr("Key recovery request sent")
var STR_QML_1053 = qsTr("For security, the key recovery request needs to be approved by at least another keyholder. Please resume once the request has been approved.")

var STR_QML_1054 = qsTr("Key recovery approved")
var STR_QML_1055 = qsTr("The keyholder can now continue with the key recovery process on their device.")

var STR_QML_1056 = qsTr("A recovery request for this key already exists.")

var STR_QML_1057 = qsTr("Key recovery requested")
var STR_QML_1058 = qsTr("To approve the key recovery, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet.")
var STR_QML_1059 = qsTr("The inheritance plan has been set up")
var STR_QML_1060 = qsTr("Update security questions")

var STR_QML_1061 = qsTr("Set up security questions")
var STR_QML_1062 = qsTr("Fill in the security questions and answers below. They will be used to prevent unauthorized access to security-sensitive features. Answers are case-sensitive.")
var STR_QML_1063 = qsTr("Please write your question")
var STR_QML_1064 = qsTr("Confirm new security questions")

var STR_QML_1065 = qsTr("Recurring payments")
var STR_QML_1066 = qsTr("Add recurring payment")
var STR_QML_1067 = qsTr("Recurring payments allow you to automatically create transactions that send bitcoins to a predefined destination wallet or addresses at scheduled intervals.")

var STR_QML_1068 = qsTr("Add recurring payment")
var STR_QML_1069 = qsTr("Please name the payment.")
var STR_QML_1070 = qsTr("Use percentage")
var STR_QML_1071 = qsTr("Please enter the amount for the payment.")
var STR_QML_1072 = qsTr("Payment name")
var STR_QML_1073 = qsTr("Fixed amount")
var STR_QML_1074 = qsTr("Please enter a percentage.")
var STR_QML_1075 = qsTr("How would you like the percentage to be calculated?")
var STR_QML_1076 = qsTr("Please specify the destination for the payment.")
var STR_QML_1077 = qsTr("Use a destination wallet")
var STR_QML_1078 = qsTr("The recurring payment will be sent to the first available (unused) addresses in the wallet. To set the destination wallet, import the wallet configuration for that wallet.")
var STR_QML_1079 = qsTr("Use whitelisted addresses")
var STR_QML_1080 = qsTr("Enter a percentage")
var STR_QML_1081 = qsTr("The recurring payment will automatically rotate among the whitelisted addresses.")
var STR_QML_1082 = qsTr("Running average")
var STR_QML_1083 = qsTr("The percentage will be calculated based on the daily average of the wallet balance over the previous period.")
var STR_QML_1084 = qsTr("Just-in-time")
var STR_QML_1085 = qsTr("The percentage will be calculated based on the wallet balance on the day of the payment.")
var STR_QML_1086 = qsTr("Use fixed amount")

var STR_QML_1087 = qsTr("BSMS/descriptors")
var STR_QML_1088 = qsTr("Coldcard")
var STR_QML_1089 = qsTr("QR code")
var STR_QML_1090 = qsTr("Select your import format")

var STR_QML_1091 = qsTr("First address of wallet")
var STR_QML_1092 = qsTr("Configuration details (visible to you only)")
var STR_QML_1093 = qsTr("Remove wallet configuration")
var STR_QML_1094 = qsTr("More")

var STR_QML_1095 = qsTr("Please set the frequency of the payment.")
var STR_QML_1096 = qsTr("Repeat")
var STR_QML_1097 = qsTr("Every day")
var STR_QML_1098 = qsTr("Every week")
var STR_QML_1099 = qsTr("Every month")
var STR_QML_1100 = qsTr("Every three months")
var STR_QML_1101 = qsTr("Every six months")
var STR_QML_1102 = qsTr("Every year")
var STR_QML_1103 = qsTr("Date range")
var STR_QML_1104 = qsTr("Start date")
var STR_QML_1105 = qsTr("End date")
var STR_QML_1106 = qsTr("No end date")

var STR_QML_1107 = qsTr("Please select the fee rate for the recurring payment.")
var STR_QML_1108 = qsTr("Priority fee rate")
var STR_QML_1109 = qsTr("Typically allow the payment to be confirmed in 1 block. Recommended if the payment is of time-sensitive nature or must be reliably settled at the earliest.")
var STR_QML_1110 = qsTr("Standard fee rate")
var STR_QML_1111 = qsTr("Typically allow the payment to be confirmed in 2 blocks.")
var STR_QML_1112 = qsTr("Economy fee rate")
var STR_QML_1113 = qsTr("Typically allow the payment to be confirmed in 3 blocks or more. Maximum fee savings. However when fees spike it could take much longer and the payment might subsequently need to be fee-bumped and signed again.")

var STR_QML_1114 = qsTr("Change date")
var STR_QML_1115 = qsTr("Please note that the date that you’ve chosen for the start date might not repeat for the cycle selected.")

var STR_QML_1116 = qsTr("Would you like to allow the platform key to automatically co-sign the payment?")
var STR_QML_1117 = qsTr("Allow platform key to co-sign")
var STR_QML_1118 = qsTr("The recurring payment will only require 1 signature from any keyholder.")
var STR_QML_1118_3_5 = qsTr("The recurring payment will require 2 signatures from the keyholders.")
var STR_QML_1119 = qsTr("Don’t allow platform key to co-sign")
var STR_QML_1120 = qsTr("The recurring payment will require 2 signatures from the keyholders.")
var STR_QML_1120_3_5 = qsTr("The recurring payment will require 3 signatures from the keyholders.")
var STR_QML_1121 = qsTr("Skip")

var STR_QML_1122 = qsTr("Would you like to add a transaction note to this recurring payment?")

var STR_QML_1123 = qsTr("Recurring payment")
var STR_QML_1124 = qsTr("This recurring payment enable the platform key to automatically co-sign. Only 1 signature (from any keyholder) is required for each payment.")
var STR_QML_1124_3_of_5 = qsTr("This recurring payment enables the platform key to automatically co-sign. Two signatures (from any keyholder) are required for each payment.")
var STR_QML_1125 = qsTr("Destination (wallet)")
var STR_QML_1126 = qsTr("Payments will be sent to the first available addresses in the wallet.")
var STR_QML_1127 = qsTr("Fee rate")
var STR_QML_1128 = qsTr("Destination (whitelisted addresses)")
var STR_QML_1129 = qsTr("Address")
var STR_QML_1130 = qsTr("Authorize recurring payment")

var STR_QML_1131 = qsTr("Enter addresses")
var STR_QML_1132 = qsTr("Batch import")
var STR_QML_1133 = qsTr("Add address")

var STR_QML_1134 = qsTr("Remove")
var STR_QML_1135 = qsTr("Addresses")
var STR_QML_1136 = qsTr("To include multiple addresses, separate them by line-breaks.")
var STR_QML_1137 = qsTr("Sort")
var STR_QML_1138 = qsTr("Reset")

var STR_QML_1139 = qsTr("Sort by start date")
var STR_QML_1140 = qsTr("Sort oldest to newest")
var STR_QML_1141 = qsTr("Sort newest to oldest")
var STR_QML_1142 = qsTr("Sort by payment name")
var STR_QML_1143 = qsTr("Sort A → Z")
var STR_QML_1144 = qsTr("Sort Z → A")
var STR_QML_1145 = qsTr("Cancel this payment")

var STR_QML_1146 = qsTr("To cancel this recurring payment, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet.")
var STR_QML_1147 = qsTr("A recurring payments allow you to automatically create transactions that send bitcoins to a predefined destination wallet or addresses at scheduled intervals.")
var STR_QML_1148 = qsTr("The recurring payment needs to be approved by all keyholders in the group wallet, and can be canceled by any keyholder at any time.")
var STR_QML_1149 = qsTr("Recurring payment request")
var STR_QML_1150 = qsTr("<b>%1</b> (%2)  is requesting to add a recurring payment.")
var STR_QML_1151 = qsTr("Review recurring payment")
var STR_QML_1152 = qsTr("Are you sure you want to cancel this recurring payment?")
var STR_QML_1153 = qsTr("Cancel recurring payment")

var STR_QML_1154 = qsTr("Are you sure you want to cancel pending cancellation of recurring payments?")
var STR_QML_1155 = qsTr("Continue to cancel the recurring payment <b>%1</b>.")
var STR_QML_1156 = qsTr("Are you sure you want to cancel this pending wallet?")

var STR_QML_1157 = qsTr("Are you sure you want to cancel this change?")
var STR_QML_1158 = qsTr("Existing Nunchuk wallet")
var STR_QML_1159 = qsTr("Are you sure you want to deny this recurring payment?")
var STR_QML_1160 = qsTr("No transaction note")

var STR_QML_1161 = qsTr("Export XPUBs from COLDCARD")
var STR_QML_1162 = qsTr("Navigate to Advanced/Tools → Export Wallet → Generic JSON → 1 → Enter Account # (0 if first time) → OK.")

var STR_QML_1163 = qsTr("Import XPUBs into this app")
var STR_QML_1164 = qsTr("Next, import the file from step 3.")

var STR_QML_1165 = qsTr("Import file")
var STR_QML_1166 = qsTr("New account data needed. Please use the mobile app to scan your device so that the new account can be loaded.")
var STR_QML_1167 = qsTr("The account imported does not match the account that you entered (%1). Please try again.")
var STR_QML_1168 = qsTr("Please enter a valid date.")
var STR_QML_1169 = qsTr("Key fingerprint does not match. Please make sure that you use the correct key device.")
var STR_QML_1170 = qsTr("Observing")
var STR_QML_1171 = qsTr("Would you like to customize the account used for this key? Using a new account per wallet helps prevent key reuse and improve privacy.")
var STR_QML_1172 = qsTr("Last used account")
var STR_QML_1173 = qsTr("New account")
var STR_QML_1174 = qsTr("Old fee rate")
var STR_QML_1175 = qsTr("New fee rate")
var STR_QML_1176 = qsTr("The new fee rate must be higher than the old fee rate.")
var STR_QML_1177 = qsTr("Create transaction with new fee rate")
var STR_QML_1178 = qsTr("Cancel the pending transaction by sending the bitcoins back to the wallet.")
var STR_QML_1179 = qsTr("Wallet address")
var STR_QML_1180 = qsTr("Customize destination")
var STR_QML_1181 = qsTr("Cancel the pending transaction by changing the recipient’s address.")
var STR_QML_1182 = qsTr("New recipient’s address")
var STR_QML_1183 = qsTr("New fee rate must be higher than old fee rate")
var STR_QML_1184 = qsTr("Invalid address")
var STR_QML_1185 = qsTr("Set alias")
var STR_QML_1186 = qsTr("The alias will show up as the wallet name locally on your devices. Removing \n \
the alias will revert the wallet name back to the default name set by the group.")
var STR_QML_1187 = qsTr("Wallet alias")
var STR_QML_1188 = qsTr("Wallet aliases used by other members")
var STR_QML_1189 = qsTr("Remove alias")
var STR_QML_1190 = qsTr("Change alias")
var STR_QML_1191 = qsTr("Alias removed")
var STR_QML_1192 = qsTr("Are you sure you want to remove this alias?")
var STR_QML_1193 = qsTr("Edit primary owner")
var STR_QML_1194 = qsTr("Primary owner")
var STR_QML_1195 = qsTr("Who is the primary owner of this wallet?")
var STR_QML_1196 = qsTr("The name of primary owner will be used to index and organize your wallets.")
var STR_QML_1197 = qsTr("Alias has been set")
var STR_QML_1198 = qsTr("Default name")
var STR_QML_1199 = qsTr("Primary owner updated")
var STR_QML_1200 = qsTr("Force sync")
var STR_QML_1201 = qsTr("Health check history")
var STR_QML_1202 = qsTr("No history")
var STR_QML_1203 = qsTr("Card ID")
var STR_QML_1204 = qsTr("Reminder")
var STR_QML_1205 = qsTr("Not checked yet")
var STR_QML_1206 = qsTr("Health check succeeded")
var STR_QML_1207 = qsTr("Transaction signed")
var STR_QML_1208 = qsTr("Sign message")
var STR_QML_1209 = qsTr("Copy signature")
var STR_QML_1210 = qsTr("Export signature")
var STR_QML_1211 = qsTr("Derivation path")
var STR_QML_1212 = qsTr("Signature copied")
var STR_QML_1213 = qsTr("The platform key's co-signing policies will be updated as below.")
var STR_QML_1214 = qsTr("The inheritance plan for <b>%1</b> will be canceled.")
var STR_QML_1215 = qsTr("The Activation Date for the inheritance plan for <b>%1</b> will change from <b>%2</b> to <b>%3</b>.")
var STR_QML_1216 = qsTr("Connected")
var STR_QML_1217 = qsTr("Disconnected")
var STR_QML_1218 = qsTr("How will you use Nunchuk?")
var STR_QML_1219 = qsTr("Assisted wallet")
var STR_QML_1220 = qsTr("For those who are new to Bitcoin, need expert guidance, or want advanced features such as inheritance planning or multi-user wallets.")
var STR_QML_1221 = qsTr("Unassisted wallet")
var STR_QML_1222 = qsTr("For those who are comfortable with doing everything themselves.")
var STR_QML_1223 = qsTr("I’ll explore on my own")
var STR_QML_1224 = qsTr("Freely create hot wallets, watch-only wallets, or state-of-the-art multisig wallets that work with a plethora of hardware signing devices. Choose one that fits your need. \n \
\n \
To quickly create a hot wallet for immediate use, click the button below. You can back it up later.")
var STR_QML_1225 = qsTr("Create a hot wallet now")
var STR_QML_1226 = qsTr("Hot wallet")
var STR_QML_1227 = qsTr("A hot wallet is a wallet that is frequently connected to the Internet. \n \
\n \
For securing large amounts of funds, consider moving to a cold wallet, a multisig wallet or an assisted multisig wallet for better security.")
var STR_QML_1228 = qsTr("Learn more about assisted wallet")
var STR_QML_1229 = qsTr("An assisted wallet is a wallet that comes with expert guidance and help along every step of your Bitcoin journey, either from a qualified Bitcoin Advisor or our platform. Here are some of the things that you can do with an assisted wallet:")

var STR_QML_1230 = qsTr("No single point of failure")
var STR_QML_1231 = qsTr("Eliminate single points of failure by using multisig: two keys are always required for spending. The loss of any one key will not compromise your funds.")
var STR_QML_1232 = qsTr("Inheritance planning")
var STR_QML_1233 = qsTr("Plan your inheritance in a non-custodial way and ensure that your bitcoins can be safely passed on to your loved ones. Compatible with existing estate plans.")
var STR_QML_1234 = qsTr("Emergency lockdown")
var STR_QML_1235 = qsTr("Lock your wallet access when there is a security threat or when you go off the grid.")
var STR_QML_1236 = qsTr("Flexible spending policies")
var STR_QML_1237 = qsTr("Set up scheduled payments, extra security measures when withdrawing large amounts of bitcoins, and more.")
var STR_QML_1238 = qsTr("Cloud backups and assisted recovery")
var STR_QML_1239 = qsTr("Have peace of mind knowing that your wallet backups are encrypted and stored securely in the cloud. Assisted recovery is a breeze.")
var STR_QML_1240 = qsTr("In-app chat support")
var STR_QML_1241 = qsTr("Chat to an expert directly within the app when you run into issues.")
var STR_QML_1242 = qsTr("Hardware key discounts")
var STR_QML_1243 = qsTr("Get exclusive discounts when purchasing hardware signing devices from our partners.")
var STR_QML_1244 = qsTr("I don’t have an advisor")
var STR_QML_1245 = qsTr("I have an advisor")
var STR_QML_1246 = qsTr("Here are some of the things that you can do with an assisted wallet:")
var STR_QML_1247 = qsTr("Get more out of Nunchuk with an assisted wallet")
var STR_QML_1248 = qsTr("Visit our website")
var STR_QML_1249 = qsTr("Add a wallet")
var STR_QML_1250 = qsTr("Use a multisig wallet for maximum safety. A multisig wallet has multiple keys—if one is compromised, your fund is still safe.")
var STR_QML_1251 = qsTr("Create a hot wallet")
var STR_QML_1252 = qsTr("Quickly create a hot wallet for immediate use and back it up later. No existing keys required.")
var STR_QML_1253 = qsTr("Recover existing wallet")
var STR_QML_1254 = qsTr("Recover hot wallet")
var STR_QML_1255 = qsTr("Create now")
var STR_QML_1256 = qsTr("Your advisor should have sent you an invitation to join a group wallet. If you don’t see one yet, ask them to resend the invitation. \n \n If you already signed up, please sign in.")
var STR_QML_1257 = qsTr("Select a country")
var STR_QML_1258 = qsTr("Learn more about Nunchuk assisted services")
var STR_QML_1259 = qsTr("Send query")
var STR_QML_1260 = qsTr("If you are looking for a white-glove, personalized service offered by a Bitcoin Advisor, enter your country and email address below, and we’ll send you the best Bitcoin Advisors in your area. \n \n Alternatively, check out the assisted services offered by our platform.")
var STR_QML_1261 = qsTr("Create new assisted wallet (%1 remaining)")
var STR_QML_1262 = qsTr("Create a new wallet")
var STR_QML_1263 = qsTr("Your email address")
var STR_QML_1264 = qsTr("Your country")

var STR_QML_1265 = qsTr("Please write down the seed phrase. It’s the backup for your key.")
var STR_QML_1266 = qsTr("Seed phrase")
var STR_QML_1267 = qsTr("Do it now")
var STR_QML_1268 = qsTr("This action cannot be repeated. Please make sure that you are ready before proceeding.")
var STR_QML_1269 = qsTr("Please take a moment to write down this seed phrase. It’s the backup for your key. <b>This app will only show the seed phrase once.</b>")
var STR_QML_1270 = qsTr("Never share the recovery phrase with anyone. Avoid having a digital copy.")
var STR_QML_1271 = qsTr("Confirm seed phrase")
var STR_QML_1272 = qsTr("Please confirm the seed phrase.")
var STR_QML_1273 = qsTr("<b>You won’t be able to view the seed phrase again in the app.</b> Please make sure that you have it backed up, or risk losing your funds.")
var STR_QML_1274 = qsTr("Review seed phrase")
var STR_QML_1275 = qsTr("I’ve backed it up")
var STR_QML_1276 = qsTr("I’ll do it later")
var STR_QML_1277 = qsTr("The security questions and answers will be updated.")
var STR_QML_1278 = qsTr("Cancel request")

var STR_QML_1279 = qsTr("Export as BC-UR2 QR (legacy)")
var STR_QML_1280 = qsTr("Export as BC-UR2 QR")
var STR_QML_1281 = qsTr("Matrix-based collaborative wallet")
var STR_QML_1282 = qsTr("Currently, TAPSIGNER, Ledger, Trezor and Software keys are compatible with the Keyholder (limited) role.")
var STR_QML_1283 = qsTr("This key (%1) already exists. Do you want to change the key type?")
var STR_QML_1284 = qsTr("<b>This action will delete the software key from this device.</b>")
var STR_QML_1285 = qsTr("Please select the key type")
var STR_QML_1286 = qsTr("Finney")
var STR_QML_1287 = qsTr("Finney Pro")
var STR_QML_1288 = qsTr("Scan QR")
var STR_QML_1289 = qsTr("The software key (%1) was upgraded to a hardware key from another device. Do you want to remove the software key from this device?")
var STR_QML_1290 = qsTr("The software key (%1) will be removed from this device. \n Please tap ‘Delete key’ to confirm.")
var STR_QML_1291 = qsTr("Delete key")
var STR_QML_1292 = qsTr("Whom do you like to request signature from?")
var STR_QML_1293 = qsTr("Select a member")
var STR_QML_1294 = qsTr("Multiple subcriptions")
var STR_QML_1295 = qsTr("Select mainnet server")
var STR_QML_1296 = qsTr("Manage mainnet server")
var STR_QML_1297 = qsTr("Mainnet server")
var STR_QML_1298 = qsTr("Add server")
var STR_QML_1299 = qsTr("Enter the server’s address")
var STR_QML_1300 = qsTr("Keep group chat history for:")
var STR_QML_1301 = qsTr("For instructions on how to connect to your own node, please refer to <a href='%1' style=\"color:#031F2B\">this guide</a>.")
var STR_QML_1302 = qsTr("New email")
var STR_QML_1303 = qsTr("Change email")
var STR_QML_1304 = qsTr("Update email")
var STR_QML_1305 = qsTr("Confirm email")
var STR_QML_1306 = qsTr("To change the email address associated with the account, you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet.")
var STR_QML_1307 = qsTr("Changing email from <b>%1</b> to <b>%2.</b>")
var STR_QML_1308 = qsTr("Cancel change")
var STR_QML_1309 = qsTr("Email is invalid")
var STR_QML_1310 = qsTr("New email is the same as the current email")
var STR_QML_1311 = qsTr("Set up reminders to health check your keys.")
var STR_QML_1312 = qsTr("Add reminder")
var STR_QML_1313 = qsTr("Select which keys you want to set up reminders for.")
var STR_QML_1314 = qsTr("How often would you like to health check these keys?")
var STR_QML_1315 = qsTr("No reminder")
var STR_QML_1316 = qsTr("Repeat every month")
var STR_QML_1317 = qsTr("Repeat every 3 months")
var STR_QML_1318 = qsTr("Repeat every 6 months")
var STR_QML_1319 = qsTr("Repeat every year")
var STR_QML_1320 = qsTr("How often would you like to health check this key?")
var STR_QML_1321 = qsTr("The keys have set periodic reminders")
var STR_QML_1322 = qsTr("Every month")
var STR_QML_1323 = qsTr("Every 3 months")
var STR_QML_1324 = qsTr("Every 6 months")
var STR_QML_1325 = qsTr("Every year")
var STR_QML_1326 = qsTr("Every 5 minutes")
var STR_QML_1327 = qsTr("Repeat every 5 minutes")
var STR_QML_1328 = qsTr("Saved addresses")
var STR_QML_1329 = qsTr("Your wallets")
var STR_QML_1330 = qsTr("Health check reminder")
var STR_QML_1331 = qsTr("Skip health check")
var STR_QML_1332 = qsTr("Saved addresses")
var STR_QML_1333 = qsTr("Add a new address")
var STR_QML_1334 = qsTr("Save an address for subsequent uses.")
var STR_QML_1335 = qsTr("Remove from saved addresses")
var STR_QML_1336 = qsTr("Are you sure you want to remove <b>%1</b> from the saved addresses?")
var STR_QML_1337 = qsTr("Select a destination")
var STR_QML_1338 = qsTr("For privacy and security reasons, reusing addresses is generally not recommended in Bitcoin. Only save and reuse an address if you must.")
var STR_QML_1339 = qsTr("Address of recipient %1")
var STR_QML_1340 = qsTr("Cancel key replacement")
var STR_QML_1341 = qsTr("%1 is currently being replaced.")
var STR_QML_1342 = qsTr("Please use the mobile app to continue creating a new wallet.")
var STR_QML_1343 = qsTr("If you are a wallet admin, please use the mobile app to continue creating a new wallet.")
var STR_QML_1344 = qsTr("For security, please note that a decrease in the co-signing delay will only become effective after an amount of time equal to the current delay has passed.")
var STR_QML_1345 = qsTr("Deactivated")
var STR_QML_1346 = qsTr("Please continue transferring funds using the mobile app.")
var STR_QML_1347 = qsTr("Please replace key(s) using the mobile app.")
var STR_QML_1348 = qsTr("View policies")
var STR_QML_1349 = qsTr("Please enter the master private key (XPRV).")
var STR_QML_1350 = qsTr("Recover key via XPRV")
var STR_QML_1351 = qsTr("Recover existing seed")
var STR_QML_1352 = qsTr("Replace key(s) in an assisted wallet")
var STR_QML_1353 = qsTr("Please replace the inheritance key via the mobile app.")
var STR_QML_1354 = qsTr("Recover a key via XPRV")
var STR_QML_1355 = qsTr("Please continue setting up the inheritance plan using the mobile app.")
var STR_QML_1356 = qsTr("Sign in via digital signature")
var STR_QML_1357 = qsTr("Please select your account type")
var STR_QML_1358 = qsTr("I have a paid subscription")
var STR_QML_1359 = qsTr("I have a Primary Key account")
var STR_QML_1360 = qsTr("To verify that you are the account owner, please enter the master public key (XPUB) of one of the keys in your assisted wallets. You can find the XPUBs in your wallet configuration (BSMS file). You can also paste in the entire BSMS file.")
var STR_QML_1361 = qsTr("Enter XPUB")
var STR_QML_1362 = qsTr("To sign in to your account,  you will be asked to sign a dummy transaction that sends 10,000 sat (%1 %2) to your own wallet.")
var STR_QML_1363 = qsTr("Replace key(s)")
var STR_QML_1364 = qsTr("If a key in a wallet is lost or has been compromised, you can replace it here.")
var STR_QML_1365 = qsTr("Note that replacing a key with a new one will create a brand new wallet. You will need to transfer the existing balance over to the new wallet afterwards.")
var STR_QML_1366 = qsTr("Which key would you like to replace?")
var STR_QML_1367 = qsTr("Replace one or multiple keys.")
var STR_QML_1368 = qsTr("Replace")
var STR_QML_1369 = qsTr("Continue to create a new wallet")
var STR_QML_1370 = qsTr("Back up the key")
var STR_QML_1371 = qsTr("The backup will allow you to recover the key in worst case scenarios.")
var STR_QML_1372 = qsTr("Keep this device safe")
var STR_QML_1373 = qsTr("Since the software key resides on this device, keeping the device safe will prevent the software key from being compromised.")
var STR_QML_1374 = qsTr("Upgrade software keys to hardware keys for improved security.")
var STR_QML_1375 = qsTr("A new wallet that includes the new key(s) has been created. The new wallet will get the original wallet’s name. The original wallet will be renamed as [DEPRECATED]%1.")
var STR_QML_1376 = qsTr("For best security, please keep your keys stored in physically distributed locations.")
var STR_QML_1377 = qsTr("Congratulations! A new wallet has been created")
var STR_QML_1378 = qsTr("Create new seed")
var STR_QML_1379 = qsTr("Are you sure you want to cancel the key replacement?")
var STR_QML_1380 = qsTr("Replacing key %1 (%2)")
var STR_QML_1381 = qsTr("Transfer funds")
var STR_QML_1382 = qsTr("Transfer all funds from the old wallet to <b>%1</b>.")
var STR_QML_1383 = qsTr("Remove unused keys")
var STR_QML_1384 = qsTr("Upon completion of the roll-over process, keys that are associated with your old wallet and are no longer used will automatically be removed.")
var STR_QML_1385 = qsTr("Existing balance")
var STR_QML_1386 = qsTr("By default, all existing coins will be consolidated into a single coin in the new wallet. If you want to organize and segregate your coins for various purposes, please create the transactions manually.")
var STR_QML_1387 = qsTr("I'll create transactions manually")
var STR_QML_1388 = qsTr("Continue, I’m fine consolidating all coins")
var STR_QML_1389 = qsTr("Continue to transfer funds")
var STR_QML_1390 = qsTr("Before you begin")
var STR_QML_1391 = qsTr("Please replace key(s) using the mobile app.")
var STR_QML_1392 = qsTr("Key added to wallet")
var STR_QML_1393 = qsTr("Family or group wallets")
var STR_QML_1394 = qsTr("Collaboratively create family or group wallets. Manage keys distributedly, control member access and chat privately.")
var STR_QML_1395 = qsTr("Role")
var STR_QML_1396 = qsTr("Facilitator admin")
var STR_QML_1397 = qsTr("Can add or remove group members. \nCan make changes to inheritance planning.
Can make changes to wallet policies.
Can activate emergency lockdown.
Can view key health status.
Can perform key health check.
Can perform key recovery.
Can create coin tags or collections.
Can edit transaction notes.
Can participate in group chat.
Can view transactions.
Can create transactions.
Can sign transactions.")
var STR_QML_1398 = qsTr("Can view key health status. \nCan perform key health check.
Can perform key recovery.
Can participate in group chat.
Can view transactions.
Can create transactions.
Can sign transactions.")
var STR_QML_1399 = qsTr("Can perform key health check. \nCan perform key recovery.
Can sign transactions.")
var STR_QML_1400 = qsTr("Can add group members. \nCan request key health check.
Can participate in group chat.")
var STR_QML_1401 = qsTr("Can view transactions.")
var STR_QML_1402 = qsTr("Only applicable for members who own a TAPSIGNER, Ledger or Trezor device.")
var STR_QML_1403 = qsTr("Select a role")
var STR_QML_1404 = qsTr("Only an admin can downgrade a member’s role.")
var STR_QML_1405 = qsTr("Create a new wallet using existing keys.")
var STR_QML_1406 = qsTr("<b>You won’t be able to view the seed phrase again in the app.</b> Please make sure that you have it backed up, or risk losing your funds.")
