name: Build linux release

on:
  push:
    branches: [ "*" ]
    tags:     [ "*" ]
  pull_request:
  workflow_dispatch:
    inputs:

jobs:
  build-image-and-app:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux/amd64
            arch: x86_64
            builder_tag: nunchuk-builder-linux-amd64
            artifacts: linux-x86_64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
            arch: aarch64
            builder_tag: nunchuk-builder-linux-aarch64
            artifacts: linux-aarch64

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Configure Git for private GitLab submodules
        env:
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
        run: |
          git config --global url."https://oauth2:${GITLAB_PAT}@gitlab.com/".insteadOf "https://gitlab.com/"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push builder image
        working-directory: reproducible-builds
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.arch }} \
            -f linux.Dockerfile \
            -t ghcr.io/${{ github.repository }}/${{ matrix.builder_tag }} \
            --cache-from type=registry,ref=ghcr.io/${{ github.repository }}/builder-cache \
            --cache-to   type=registry,ref=ghcr.io/${{ github.repository }}/builder-cache,mode=max \
            --push .

      - name: Build application
        run: |
          docker run --platform ${{ matrix.platform }} --rm \
            -v ${{ github.workspace }}:/nunchuk-desktop \
            -w /nunchuk-desktop \
            ghcr.io/${{ github.repository }}/${{ matrix.builder_tag }} \
            bash reproducible-builds/linux.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifacts }}
          path: build/artifacts
          compression-level: 0
